### ISSUE TITLE
Serialize JSON output

### ISSUE THREAD

**Issue by davepwsmith** [yabwe/medium-editor#1008]
Is there a reason that the contents of an element are wrapped in a deeper level of json? If there were several pieces of information available that might be useful, but here we just have` Element: { value: x } ` were a simple `Element: x` would surely suffice?

**Comment by nmielnik** [comment]
My best guess is that there was an expectation that there would eventually be additional information exposed about each element within the editor in these sub-objects (the attributes on the element, information about the selection, etc.).

There isn't anything exposed now, but it would make sense to expose a bit more in the future.  Since changing the structure the JSON in a way that you described would not be backwards compatible, it would require a major release to change.  

I would be in favor of keeping the format as-is just so we have the flexibility to add data without a major release moving forward.  Is this format causing any issues or is this just a suggestion to make things shorter?

**Comment by davepwsmith** [comment]
If the intention is to expose more data, then I guess it's best to leave it as it is. I'm just a fan of keeping things as simple as possible if there's no need for them to be more complicated.

**Comment by nmielnik** [comment]
@davepwsmith you are right, it's best to keep things as simple as they can be until there's a need for more complexity.

I think in this case it was just implemented in a not-so-simple way to start, and now it's more painful to go back to the simple approach, if that makes any sense.  Your suggestion would have been a better approach at the time this was implemented.
