### ISSUE TITLE
Pasting HTML into an editor object

### ISSUE THREAD

**Issue by scripting** [yabwe/medium-editor#1016]
In my application, I want the user to be able to paste HTML into a medium-editor object and have it not be neutered, i.e. to not have < converted to &amp;lt;

I used the "paste" options to set this up, per the docs, but when I paste in HTML it still gets neutered.

http://myword.io/testing/hellomediumeditor.html

That's my test app.

When I enter &lt;s>hello&lt;/s> it appears as the HTML, not as hello with a strikethrough.

You can see by viewing source that it creates the medium-editor object as:

```js
theEditorObject = new MediumEditor (".divEditor", {
	paste: {
		forcePlainText: false,
		cleanPastedHTML: false,
		cleanReplacements: [],
		cleanAttrs: ['class', 'style', 'dir'],
		cleanTags: ['meta']
		},
	placeholder: {
		text: "This is a good place to tell your story..."
		},
	toolbar: {
		buttons: ["bold", "italic", "underline"],
		},
	buttonLabels: "fontawesome"
	});
```

I've tried all the permutations I can think of. 

Any help would be appreciated.

**Comment by scripting** [comment]
Follow-up -- the problem isn't quite that simple.
If I select some text on a web page and paste it into my demo app, the styles are preserved.
But suppose you copy the &lt;embed> code from a YouTube video and want it to be seen as HTML in medium-editor? How>??

**Comment by nmielnik** [comment]
Hey Dave, glad to see you're still using the editor for your project.

So issues with copy and paste are tricky especially when you're dealing with copying content directly from a browser.  When you copy html rendered out on a page, which may or may not have formatting, what the operating system puts in the clipboard is something that when pasted, will preserve that formatting.  For something like Word, if you copy text that is bold, italic, etc., when you try to paste that into a contenteditable field, the OS will attempt to preserve that formatting by adding in `<b>`/`<strong>` tags, but in the underlying HTML (so what you'll see pasted will be "**bold text**" instead of "\<b\>bold text\</b\>")

As an example, you can create a contenteditable element in a page (ie `<div contenteditable="true"></div>`) and attach to the `paste` event on that element.  When you try to copy and paste something in, dump the value of `event.clipboardData.getData('text/html')` and you can see how the browser plans on translating the copied text (it varies from browser to browser and from OS to OS, and there likely won't be any value at all for Internet Explorer).

So, if you copy a) "<s>strikethrough</s>" vs b) "\<s\>strikethrough\</s\>" and try to paste it into a contenteditable field, for a) the browser will attempt to inject `<s>` tags, and for b) it will preserve the `<` correctly.

I'm not sure if it will actually work, but if you want to try to copy and paste a video into the editor, you wouldn't copy the text `<embed>`, you'd want to find an actually rendered video, highlight it, and attempt to copy and paste it.  I'm not sure if it will work, but it would be the simplest thing to try first.

Otherwise, you'll likely need to create some sort of extension to handle this. The extension could be a form button in the toolbar (similar to the link extension) which allows the user to type the url of a video, and then manually injects an `<embed>` tag.  The extension could also override the paste extension, and try to detect if `&gt;embed&lt;` is in the pasted html, in which case it will convert it into an actual `<embed>` tag that it injects directly into the editor.  There may be other ways to try to do this, but those are the first few that come to mind.

Apologies if this wasn't what you were asking, this is my best attempt to try to explain why I think you're seeing the behavior you're seeing, and what could be other ways to accomplish what you're describing.

**Comment by scripting** [comment]
Thanks Nate -- that _is_ what I was asking about.

I remember from doing Mac apps a long time ago how the clipboard worked there, and I inferred it must be working the same here. Your answer confirms that it does.

However -- it still is important to be able to, somehow, get that <embed> element into my post, by just copying and pasting the text that's offered in the web page on YouTube. There's no way to get them to change how that works, nor would want them to change it. People understand what to do, it works with WordPress, and therefore I need to find a way to make it work with the software I'm building. 

Here's another possible approach.

User visits YouTube, copies the <embed> element to the clipboard, switches into 1999.io (my app) and instead of pasting, they choose a command from a menu -- "Insert text". A dialog appears, the user pastes in the text, clicks Submit and the code in the dialog does whatever it has to do to get it inserted as HTML into the current medium-editor object.

The question is -- is there any way to insert arbitrary HTML into a medium-editor object under program control? That would be an acceptable solution.

Dave

**Comment by nmielnik** [comment]
So I think you'll be able to accomplish the insertion of arbitrary html by calling [`editor.pasteHTML()`](https://github.com/yabwe/medium-editor/blob/master/API.md#pastehtmlhtml-options).  This will allow you to replace whatever is currently selected by the user (or wherever the cursor currently is) with some arbitrary HTML.

The documentation isn't great, but you can look at the source code to see the kind of options you can pass in [here](https://github.com/yabwe/medium-editor/blob/master/src/js/extensions/paste.js#L194-L222).

If this method works the way you want, you can build a custom extension which could act as a button in the toolbar that the user could click to insert the arbitrary html (this would be a really useful extension that I bet a lot of folks would like to have).  You could also just build out your own custom UX outside of medium-editor, and just use the `.pasteHTML()` method to inject the html.

**Comment by scripting** [comment]
Wellll -- that worked! ;-)

Here's a test page. 

http://myword.io/testing/testpaste.html

Type some text in the top, and click the Paste HTML button.

A YouTube video appears.

Bing! 

Dave

**Comment by scripting** [comment]
Follow-up -- 

As reported in previous message, pasteHTML works in a demo app, however it does not work in the 1999.io app, which is quite a bit more complicated, of course.

It won't be long before the app is public, then I'll revisit it, and hopefully someone else can spot the problem.

**Comment by nmielnik** [comment]
@scripting would you mind sharing what you did to get around your issue?  Just as a point of reference for others who look at this issue in the future.

**Comment by scripting** [comment]
Sorry I missed your last question to me. 

I had tried using pasteHTML in 1999.io and it didn't work. 

So after you suggested that it does what I needed, I tried it in a standalone minimal app. Where it worked.

http://myword.io/testing/testpaste.html

I tried again in the "real" app and it still didn't work.

So I didn't get to the bottom of what the problem is. 

There is working code in the minimal app, and I'm leaving it there for others to look at, in case anyone has the problem in the future. 

I run a bunch of communities myself so I understand how important it is to leave a trail for others to follow. ;-)

Dave
