### ISSUE TITLE
Set style to current selection?

### ISSUE THREAD

**Issue by oknoorap** [yabwe/medium-editor#1045]
How to set style of selection range? e.g I want to wrap text with <span style="font-size: 10px">text</span>, I've followed wiki but still confusing.

```
var IncreaseFontSize = MediumEditor.extensions.button.extend({
	name: 'increaseFont',
	tagNames: ['span'],
	contentDefault: '<i class="uk-icon-plus"></i>',
	init: function () {
		MediumEditor.extensions.button.prototype.init.call(this);
	},
	handleClick: function (e) {
		e.preventDefault();
		e.stopPropagation();

		let range = MediumEditor.selection.getSelectionRange(this.document);
		console.log(range)

		return;
	}
});
```

**Comment by orthes** [comment]
You have two options how to manipulate selected text:

1. You can call [`this.execAction()`](https://github.com/yabwe/medium-editor/blob/5.15.1/src/js/extensions/README.md#execactionaction-opts) for built-in actions (like bold, font size, etc.) - example: https://github.com/yabwe/medium-editor/blob/5.15.1/src/js/extensions/fontsize.js#L154
2. Or you can use [rangy](https://github.com/timdown/rangy) as shown here - https://github.com/yabwe/medium-editor/blob/5.15.1/src/js/extensions/WALKTHROUGH-BUTTON.md#4-handle-button-click

If you want to wrap text with some other text, you can try to use rangy's [`pasteHtml`](https://github.com/timdown/rangy/wiki/Text-Range-Module#pastehtmlstring-html) function

**Comment by oknoorap** [comment]
@orthes can you give me an example, and what is pasteHTML available options?
my code right now, inside handleClick

```
let span = document.createElement('span'),
range = MediumEditor.selection.getSelectionRange(this.document)

range.surroundContents(span)
span.className = 'font-size'
span.style.fontSize = '14px'
span.setAttribute('data-font-size', size)
```

I don't know what to do next, basically I must using execAction, but I love using span, because font tag is kinda old.

**Comment by orthes** [comment]
Then try to use this:

```javascript
init: function () {
    this.classApplier = rangy.createCssClassApplier('font-size', {
        elementTagName: 'span',
        normalize: true,
        elementAttributes: {
            style: 'font-size: 14px',
            'data-font-size': 14
        }
    });
    // ...
},

handleClick: function (event) {
    this.classApplier.toggleSelection();
}
```

Take a look at createCssClassApplier function - https://github.com/timdown/rangy/wiki/Class-Applier-Module#rangycreateclassapplierstring-theclass-object-options-array-tagnames

**Comment by oknoorap** [comment]
I got rangy.createCssClassApplier is not a function, I'm sorry asked too many question, but what happen? I've initialized rangy before 

```var IncreaseFontSize = MediumEditor.extensions.button.extend```

**Comment by orthes** [comment]
Try to reproduce the problem on https://jsfiddle.net/. Without that I'm unable to help you any further.

**Comment by oknoorap** [comment]
okay I got it, rangy modules in different js, I have to load it separately. Okay now, can rangy add increment to existing css properties?

**Comment by orthes** [comment]
I don't know. I don't have much experience with rangy myself. You'll have to go to their documentation. If you have more issues with rangy, please report them there. As far as medium-editor is concerned, I'm closing this issue.

**Comment by oknoorap** [comment]
Is there any method in medium editor that doesn't use rangy? but not using execCommand. Like what I describe, I want to increase font size but with span tag. Maybe in the next future I hope the fontsize button doesn't use range slider.

**Comment by orthes** [comment]
https://github.com/yabwe/medium-editor/blob/5.15.1/API.md#editor-action-functions

**Comment by nmielnik** [comment]
A built-in function that can wrap a selection in a tag or create a span with a class name has been a desire of mine for a long time, it just hasn't been added into the codebase.

So, like @orthes mentioned above, your options are either relying on the browser's built in font-size increase/decrease, or using something like rangy's cssclassapplier to add your own tag/class names.

**Comment by phiggins42** [comment]
I had a similar issue, where I had to wrap an arbitrary selections with <mark> elements, but ran into _several_ issues that prevented "simply taking the selection html and wrapping it in a element". Seems like this is good boilerplate for this usecase ... there were lots of times when the selection would traverse multiple nodes, or break existing nodes in half and whatnot ... in order to pull it off (although a bit convoluted, but ended up being a well-working solution to all the ambiguity of various nodes and behaviors):

* get selection html into a fragment
* save the selection (via util.selection tools)
* change all the <a> tags in the fragment to <span> tags with some identifier, like <span data-preserved-link>
* execCommand('createLink') on the selection 
* (at this point you'll have 1 <a> tag wrapped around 0-or-more <span> tags)
* convert the <a> tags to your custom element. 
* convert all the remaining span tags back to <a> tags
* restore the selection

no you have a selection wrapped in any element you want, preserving how it would naturally break across <p> and <div> and other tags.

hope this helps. (i have code i can share, but it's a bit of a mess, and uses jquery for some simple dom conversions so I'm a bit ashamed). it's written as an extension called "mark-anchor", and just allows you to hook the logic into a toolbar button press.
