### ISSUE TITLE
Edit link won't show anchor links

### ISSUE THREAD

**Issue by alvarotrigo** [yabwe/medium-editor#1071]
### Description

When a link is an internal anchor link medium-editor won't show when clicking over it as it does with any other link. 
This makes it impossible for the user to edit it.

### Steps to reproduce

1. Create a a link with just an anchor:  #demo 
2. Click over the text with link
3. Nothing will appear under it and won't be able to be edited.

**Expected behavior:**   The anchor link would be editable.

**Actual behavior:** Anchor links are not editable. 

**Link to an example:** https://jsfiddle.net/ay9cLgab/23/

### Versions

- medium-editor: latest
- browser: all
- OS: all

**Comment by nmielnik** [comment]
Thanks for opening an issue on this.  I'm guessing the bug is almost certain [here](https://github.com/yabwe/medium-editor/blob/master/src/js/extensions/anchor-preview.js#L179-L184) in `anchor-preview.js`.  I'm guessing something is screwed up with regex, or the assumption the code is making about what the html of the link will look like.

The mouseover behavior of the anchor preview is one of the few remaining areas we don't have code coverage for, which is a bummer because things like this can happen.

**Comment by alvarotrigo** [comment]
Yep, the second regex (`/href=["']#\S+["']/.test(target.outerHTML)`) is taking anchor URLs and therefore entering in the condition and treating them as empty URLs. 

It seems to be a reason behind it as it was intentionally coded that way.

https://regex101.com/r/eM4fT4/1

**Comment by nmielnik** [comment]
So after some digging I was able to track down the commit that added (and updated) this check: https://github.com/yabwe/medium-editor/commit/a49942fe11f0623b91aff2c3f9b818ffbf512cc1 & https://github.com/yabwe/medium-editor/commit/d614cfab6d3c7087533f1b949d96b916ae7c5ba6

Looks like this work was done as part of the fix for #167 

@daviferreira @yacomink do you fellas remember why would we want the anchor-preview to not display for links that start with `#`? I can't think of a use case where we'd want to prevent the anchor-preview from displaying when an anchor's href is `#something`...

**Comment by yacomink** [comment]
I understand looking back at the original issue what we were trying to do.
There's an interface plugin with controls that have href="#" and we didn't
want the link preview to show. Looking at it now though, this doesn't seem
like a great way to solve that problem! I generally wrap the interface
controls in some element with contentEditable="false" to accomplish the
same thing.

**Comment by nmielnik** [comment]
Thanks @yacomink , seems to me like we might want to just change this regex and allow for users to edit the href of ANY `<a>` element...

Without an argument against for @daviferreira let's just propose that as the fix for this if anyone wants to take a crack at it.

**Comment by Olgagr** [comment]
@nmielnik I think a quite nice option will be to make it configurable. By default it could be shown on all links but I can imagine that sometimes it might be not desirable.

**Comment by nmielnik** [comment]
Fixed via #1100

**Comment by alvarotrigo** [comment]
Thanks!
