### ISSUE TITLE
Calling `.focus()` on an editor sometimes throws error because window.selection is of type None

### ISSUE THREAD

**Issue by mitchellrj** [yabwe/medium-editor#1082]
### Description

Calling `.focus()` on an editor sometimes throws error because window.selection is of type None:

    Selection {
      anchorNode: null,
      anchorOffset: 0,
      baseNode: null,
      baseOffset: 0,
      extentNode: null,
      extentOffset: 0,
      focusNode: null,
      focusOffset: 0,
      isCollapsed: true,
      rangeCount: 0,
      type: "None"
    }

### Steps to reproduce

Happens sporadically on Google Chrome on pages with multiple editors.

**Expected behavior:** No error.

**Actual behavior:** Error.

### Versions

- medium-editor: 5.14.3
- browser: Chrome 50.0.2661.94 (64-bit)
- OS: Ubuntu Trusty (14.04)

**Comment by j0k3r** [comment]
Please provide a JSBin / jsfiddle containing a set of reproducible steps.

**Comment by mitchellrj** [comment]
As stated in the body: it's sporadic - not immediately reproducible.

**Comment by mitchellrj** [comment]
(It works fine if I add a `try`/`catch` block to catch the exception.)

**Comment by nmielnik** [comment]
@mitchellrj have you tried calling `editor.selectElement(element)`?  This makes sure that an element is selected for focus is triggered on the editor.  Granted, you'll need to pass it an element to select which is within the editor, but it might help shed some light on what the problem is here.

**Comment by mitchellrj** [comment]
No, this is not closed yet, please reopen.

**Comment by nmielnik** [comment]
Apologies, we hadn't heard back after submitting the suggestion, a lot of times that just means it was worked around or isn't happening anymore.

Have you tried using `editor.selectElement(element)` instead of calling `.focus()` directly?  Does this ever happen when only medium-editor is on the page?  

Honestly this is one of the first times I've heard of this so I'm curious if there is some other library or part of your application that could be causing this to happen.

**Comment by nmielnik** [comment]
@mitchellrj could you confirm whether using `.selectElement()` instead of `.focus()` avoids this issue?
