### ISSUE TITLE
Feature request: Eager detection of links

### ISSUE THREAD

**Issue by orbanbotond** [yabwe/medium-editor#1083]
### Description

"Currently the link is saved as link only if you type some additional text behind the link.
EXPECTED BEHAVIOR: The link should be saved as link if it's typed as link."

[Description of the bug or feature]

### Steps to reproduce

1.Type a link
2.do not press enter or space after it.

**Expected behavior:** [What you expected to happen]
The link should be detected.
**Actual behavior:** [What actually happened]
It is not detected unless we type a space or enter.

This is only an issue if the autoLink is specified as true.

**Comment by nmielnik** [comment]
@orbanbotond are you suggesting that there be some sort of interval, such that if the user hasn't typed anything for say, 2 seconds, the auto-link detection runs immediately?

**Comment by orbanbotond** [comment]
We are saving the content as soon as possible.
In terms of code we are subscribed to the 'editableInput' event of the editor and as soon as that is triggered we save the content.

So the 2 second delay is not good for us.
The ideal situation for us would be to detect the link as soon as possible and turn into a link then after this is done trigger the 'editableInput' event.

**Comment by nmielnik** [comment]
So the problem is that most substrings of a link are still a valid link.  So `google.co` is a valid url, as is `google.com`, `google.com/`, `google.com/v`....`google.com/voice`.

The reason the code waits for a space or a tab is to know that the text has ended and to avoid inserting a link on every keystroke.  If you did try to repeatedly 'grow' the link after each keystroke, I'm not sure if the code would detect it properly since the html after you type `google.com` would actually be:

```html
<a href="http://google.com">google.co</a>m
```

Since the `google.co` would be detected as a link first, and then the `m` might get added outside of the link.  

But, just to clarify, is this the expected behavior?

**Comment by nmielnik** [comment]
Closed this until we hear back, my guess is that this is not the desired behavior.
