### ISSUE TITLE
How should I deserialize my data back into the editor?

### ISSUE THREAD

**Issue by makeitrein** [yabwe/medium-editor#1085]
Fantastically cool plugin, need some advice about deserializing the serialized JSON representation of the editor...

Every time the user inputs into the editor, I'm storing the serialized data in Firebase. 
```
this.editor.subscribe('editableInput', (event, editable) => {
        contentRef.set(this.editor.serialize()) // my Firebase Reference
      })
```
How should I go about deserializing the data back into editor? I don't see a deserialize method, maybe just loop and setContent is the right way of going about this?

**Comment by nmielnik** [comment]
When you serialize the data, the JSON you get back is a map where the key is the id of the editable element and the value is the innerHTML.  So, one way to do this is to make sure each of the editor elements has an id attribute.  Thus, when you get the JSON, you can iterate over the keys, grab the element by id, and set its innerHTML.

Ideally, you would do this population of the elements before you actually instantiate the editor.  The reason for this is that the editor stores a cache of the innerHTML of the elements so that it can properly trigger the `editableInput` event whenever its content changes.

If you can only populate the innerHTML of the elements _after_ the editor has already been instantiated, you'll want to use the `setContent` method, which would be problematic since the method currently takes in the `index` of the element within the editors array of elements, not the id of the element itself.  This won't be a problem if you only have one element per editor, but it sounds like you have multiple elements per instance of MediumEditor correct?

You can always try setting the `innerHTML` of the the elements even after the editor has been instantiated if you're not dealing with `<textarea>` elements or needing the `editableInput` event to fire at the time you set the html.  Does that answer your question?

**Comment by jordan2b1** [comment]
Thx nmielnik, excellent explanation - I am able to populate the editor before it's been instantiated, which makes my life easier. I'll test it out tonight, see how it goes.
