### ISSUE TITLE
Can't retrieve elements from editor with serialize

### ISSUE THREAD

**Issue by jbrozena22** [yabwe/medium-editor#1101]
After starting the MediumEditor I am unable to retrieve the elements from the editor.

Example - go to http://yabwe.github.io/medium-editor/
Open the javascript console
```
var editor = new MediumEditor('.editable');
console.log(editor.serialize());
```
I would expect to see a JSON object of the elements on the page. 
Instead I return Object {} (an empty object).

Here's an example on RequireBin: http://requirebin.com/?gist=04718c5a3e728bf7a52c23ba32ef3600

I dug into the code and traced it to [here](https://github.com/yabwe/medium-editor/blob/master/src/js/core.js#L236) which came in with [this commit](https://github.com/yabwe/medium-editor/commit/4e75f71c309302c5b46882597255440a59f41ec7#diff-c1a8a21c933e1f48d90be645db83630f) 

It looks like while setting up the MediumEditor it filters the elements that can be included in the editor, and ignores elements that have the attribute 'data-medium-editor-element'. But the problem is that all MediumEditor elements have that attribute so they are always ignored when re-setting up the editor.

The only other thing I can figure is that I'm just retrieving the editor incorrectly but I can't find anything in the docs about how to retrieve an existing editor (other than saving it as a global variable which I would prefer to avoid since I have multiple editors and will get messy quick).

- medium-editor: 5.18.1
- browser: Chrome
- OS: Mac OSX

**Comment by nmielnik** [comment]
@jbrozena22 thanks for the great explanation and repro steps. 

Ideally, you'd want to call `destroy()` on the existing editor instance in which the elements are contained before you created a new instance.  `destroy()` not only removes the custom attributes from the editor, but it also removes all the event handlers from the body + editor elements, as well as remove custom elements from the page.

If you're afraid of adding a global variable, there is a "secret" global variable already being used by medium-editor ( 😲 I know!)  We store each instance of MediumEditor in `window._mediumEditors`, which is an object that can be indexed by the `.id` property of a MediumEditor instance. This is being used both to ensure we create unique ids for each instance, but also so that it's possible to take an editor element and retrieve the instance it's referring to.

Would you be able to call `destroy()` on your existing instances before creating a new one?

**Comment by jbrozena22** [comment]
Thanks for the quick reply (and awesome work on this package btw).

Yeah unfortunately I can't use destroy in this instance. Thanks for the tip on window._mediumEditors I'll use that to find my existing editor.
