### ISSUE TITLE
Error in console at link selection

### ISSUE THREAD

**Issue by MikeDevice** [yabwe/medium-editor#1151]
### Description

If text contains a link and user tries to select this link, then follow error appears in console
`Uncaught TypeError: Array.prototype.forEach called on null or undefined` 
### Steps to reproduce
1. Type some text
2. Create a link at one word
3. Select this link using mouse many times.

**Expected behavior:**
No errors in console

**Actual behavior:**
An error message outputs to the console

**Link to an example:** 
[JSFiddle](https://jsfiddle.net/quesqu21/4/)
### Versions
- medium-editor: 5.21.0
- browser:  51.0.2704.106 (64-bit)
- OS: ubuntu 14.04 LTS

**Comment by nmielnik** [comment]
Ah, I was finally able to get a repro on this! (thanks @MikeDevice).

Looks like the issue is within `events.detachDOMEvent()` and potentially `events.attachDOMEvent()`.  We need to safety check to ensure the `targets` actually exists and is an array.  Seems like with the anchor-preview mouse-out detection, there could be a case where we try to detach an event listener from an element that might not exist anymore.

**Comment by nmielnik** [comment]
You can find more discussion about this same issue as part of #1137
