### ISSUE TITLE
Add new empty row to split text

### ISSUE THREAD

**Issue by FiodorGherasimenco** [yabwe/medium-editor#1159]
### Description

Create a string `<tag><br/></tag>` and pasteHTML. For me its some kind of placeholder and after paste a string <tag> is removed.  For now my code its something like `<tag><span></span><br/></tag>` and after pasteHTML it become `<tag><br/></tag>`.  May be you can add some option to add new row in current place.

**Comment by nmielnik** [comment]
@FiodorGherasimenco I'm having trouble understanding what the feature request here is, could you try to clarify?  Perhaps walkthrough step by step and include user action, what actually happens, and what you would expect to happen?

**Comment by FiodorGherasimenco** [comment]
Impossible to paste tag that's include only one tag "br" inside its removing br + parent tag

**Comment by nmielnik** [comment]
@FiodorGherasimenco the first issue is that you'll want to use `preCleanReplacements` instead of `cleanReplacements` to make sure you replace the `<div>` with a `<p>` before the other replacement run.

I'm taking a look to see if I can figure out what is removing the `<p><br/></p>` now.

**Comment by nmielnik** [comment]
So this behavior is actually by-design, the behavior of `cleanPaste()` within the paste handler will remove any elements that only contain `<br/>`.  You can see that if you put a character inside of that `<div>` (ie `<div>x</div>` instead of `<div><br/></div>`) the element won't actually be removed.  [These lines in paste.js](https://github.com/yabwe/medium-editor/blob/master/src/js/extensions/paste.js#L405-L424) are almost certainly what is removing that `<div><br/></div>` in your example.

If you want to modify this code to not remove these `<div><br/></div>` elements, you can always override the the `cleanPaste` method of the paste handler by passing it in when you initialize medium-editor:

```js
var editor = new MediumEditor(document.getElementById('editor'), {
    'paste': {
        'forcePlainText': false,
        'cleanPastedHTML': true,
        'preCleanReplacements': [
            [/<div[^>]*?>/, '<p>'],
            [/<\/div>/, '</p>']
        ],
        cleanPaste: function (text) {
            var i, elList, tmp, workEl,
                multiline = /<p|<br|<div/.test(text),
                replacements = [].concat(
                    this.preCleanReplacements || [],
                    createReplacements(),
                    this.cleanReplacements || []);

            for (i = 0; i < replacements.length; i += 1) {
                text = text.replace(replacements[i][0], replacements[i][1]);
            }

            // your custom code to handle the rest of the paste
            //  ....
           
            return this.pasteHTML(text);
        }
  }
});
```
