### ISSUE TITLE
How to prevent pasting into medium-editor

### ISSUE THREAD

**Issue by maf10so** [yabwe/medium-editor#1205]
### Description

I have a problem with a medium-editor. I don't know how to prevent pasting into medium-editor. Maybe you know how do it.

**Comment by j0k3r** [comment]
For now, you can't disable pasting. At least I can't remember how to do that.

**Comment by paradite** [comment]
This is possible with `useCapture`option as long as you have access to the parent of the element which uses medium editor, and I think I have done this before.

- Use the `useCapture`option when binding relevant event listeners to any parent of that element
- Then use either `stopPropagation()` or `preventDefault()` within your event handler to avoid reaching medium-editor's event handler.

Reference on `useCapture`:
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener

**Comment by nmielnik** [comment]
I believe if you override the paste extension's `doPaste()` method to be a no-op, you would disable pasting in the editor altogether.  MediumEditor's custom paste handler kills the default paste event and then executes that method to actually do the pasting, so having that function do nothing should do the trick.

I'm guessing it could be as simple as this:

```js
var editor = new MediumEditor('.editor', {
    paste: {
        doPaste: function () { // no-op }
    }
});    
```

Another way to do this is following what @paradite mentioned above, where you listen to the 'paste' event of the editor element itself (or the editor's parent element), but set `useCapture` to `true` when you call `addEventListener()`.  This will allow you to catch the paste event before it propagates down to the editor element itself.  Calling `preventDefault()` on the event there should be enough since the paste extension tries to respect if `preventDefault()` was called, but worst case you can just call `stopPropagation()` and kill the event from propagating completely.
