### ISSUE TITLE
editableClick and editableKeyup is giving different event.target

### ISSUE THREAD

**Issue by sajus** [yabwe/medium-editor#1208]
### Description

editableClick and editableKeyup gives me different event targets, and editableKeyup needs to provide the proper event targets rather giving the editor instance.
### Steps to reproduce
1. Open the editor and type few lines  with different font styles for each lines
2. Using mouse, click on any one of these lines listen to editableClick and check the target font style. You will see proper styles with jQuery `$(event.target).css('font-family')` 
3. Now using keyboard move between lines, listen to editableKeyup and check the target, you will see editor instance as target. It should provide me the same target like editableClick.

**Expected behavior:** [What you expected to happen]
editableKeyup should give target as it editableClick does.

**Actual behavior:** [What actually happened]
editableClick and editableKeyup is giving different event.target
### Versions
- medium-editor:
- browser:
- OS:

**Comment by sajus** [comment]
http://stackoverflow.com/questions/18836477/onkeyup-onkeydown-events-not-firing-for-span-element

**Comment by sajus** [comment]
@j0k3r , the issue with 'editableKeyup' not getting the target element is because of `contenteditable` which doesn't drill down the event, and instead sends from the editor instance. 

Setting the editor contenteditable as false and then setting contenteditable for childnodes makes disjoint input field. Making it difficult to move between two different `<p>` using arrows. 

other solution could be using jQuery to manually capture these events, which needs to be tested. 

Do you have any inputs or suggestion to get rid of this blocking issue?

**Comment by j0k3r** [comment]
Sorry I've no input but what I know is we won't use jQuery for that.

**Comment by sajus** [comment]
Okies!

**Comment by nmielnik** [comment]
If you think about this, it doesn't make sense for an element that can't receive focus to ever be able to trigger a keyup event.  I can put focus into a textbox, a checkbox, an element with `contenteditable="true"`, etc. meaning I can click on those (or tab to them) and then start using the keyboard to type or interact with the elements.  So, it makes sense that keyboard events could fire with those elements as the target.

However, for something like a `<span>` or a `<p>`, I can't move focus to those elements, so I wouldn't expect there to be any way for a keyup, keydown, keypress, etc. event to fire with a `<span>` or a `<p>` as the target.  However, since I can actually click on those elements, I **_would_** expect for a click event to fire with those as the target.

Based on what I think you're trying to achieve @sajus , I would guess that whenever the `editableClick` or `editableKeyup` event fires, you could instead inspect the current selection and see what element are contained within the selection.  If there is nothing within the selection, and it's just a blinking cursor, I believe the element the cursor is closest to will still be retrievable when you inspect the selection.

You can check out the [MDN Selection API](https://developer.mozilla.org/en-US/docs/Web/API/Selection) to help see what all you have access to regarding the selection.  MediumEditor also exposes a bunch of helper functions around this via the `MediumEditor.selection` API.  You can find all the helpers we expose there [here](https://github.com/yabwe/medium-editor/blob/5.22.2/src/js/selection.js).  I'm guessing `MediumEditor.selection.getSelectionStart()` or `MediumEditor.selection.getSelectedParentElement()` might be the helper functions you need to figure out what element is near the cursor.
