### ISSUE TITLE
Blur event wrong working 

### ISSUE THREAD

**Issue by abdullah** [yabwe/medium-editor#1210]
### Description

If body element hasn't any height , medium editor not trigger blur event after leave/click in editable elements to body.

**Expected behavior:** When user click on body,  medium editor trigger blur event

**Actual behavior:** When user click on body,  medium editor not trigger blur event

**Link to an example:**  [JSFiddle](https://jsfiddle.net/mzv9hw5g/1/) 

### Versions

- medium-editor: 5.22.0
- browser: Chrome 52
- OS: MAC El capitan 10.11.5

**Comment by hellocosmin** [comment]
That's because the `<body>` in your example ends exactly where the last editable ends. 
So, in your example, you're not actually clicking on the `<body>`, you're clicking on JSFiddle's `<iframe>` that holds your HTML. Take a look by inspecting your example's markup on JSFiddle.

I've updated your JSFiddle to demonstrate that it works: https://jsfiddle.net/mzv9hw5g/2/
