### ISSUE TITLE
Copy paste doesn't apply the styles.

### ISSUE THREAD

**Issue by sajus** [yabwe/medium-editor#1226]
### Description

[Description of the bug or feature]

Select any text/hyperlink/image/table/bullet points, apply some styles like font color, font size etc. Copy these and paste some where else. You can see these setting to default.
### Steps to reproduce
1. Select any text
2. apply bold to these selected text
3. Copy this and paste somewhere else in the editor
4. Copied text is not bold

**Expected behavior:** [What you expected to happen]
Copied text should be bold
**Actual behavior:** [What actually happened]
Copied text is set to default

**Link to an example:** [If you're reporting a bug that's not reproducible on our [demo page](https://yabwe.github.io/medium-editor/demo.html), please try to reproduce it on [JSFiddle](https://jsfiddle.net/), [JS Bin](https://jsbin.com), [CodePen](http://codepen.io/) or a similar service and paste a link here]

You can reproduce this issue in demo page :- https://yabwe.github.io/medium-editor/demo.html
### Versions
- medium-editor: 
- browser:
- OS:

**Comment by paradite** [comment]
Hi there,

This is not a bug, the styles do not apply because the demo page uses a paste setting that forces plaintext when pasting:

```
paste: {
        /* This example includes the default options for paste,
           if nothing is passed this is what it used */
        forcePlainText: true,
        cleanPastedHTML: false,
        cleanReplacements: [],
        cleanAttrs: ['class', 'style', 'dir'],
        cleanTags: ['meta'],
        unwrapTags: []
    }
```

To allow styles, simply set `forcePlainText` to true, as shown here:
https://github.com/yabwe/medium-editor/blob/master/demo/clean-paste.html

```
        var editor = new MediumEditor('.editable', {
            buttonLabels: 'fontawesome',
            paste: {
                cleanPastedHTML: true,
                forcePlainText: false
            }
        });
```

You can try it by serving the project locally:
`python -m SimpleHTTPServer 8000` or `python2 -m SimpleHTTPServer 8000`
then go to http://localhost:8000/demo/clean-paste.html to try.

**Comment by nmielnik** [comment]
Thanks @paradite !
