### ISSUE TITLE
Dynamic Elements duplicates first unique ID

### ISSUE THREAD

**Issue by cbloss** [yabwe/medium-editor#1261]
### Description

So I've got this page that calls the Medium Editor on first load and then after an AJAX call, I use the addElements() function and it causes the ID to be off. When I try to get the base.id, all the editors have the same id. The only way I can get around this (that I've found) is to destroy and then call the setup()

### Steps to reproduce

1. 
```js
var editor = new MediumEditor('.posts', {
        toolbar: {
            buttons: [
                'bold', 
                'italic', 
                'underline', 
                'anchor',
                'tag'
            ],
            static: true,
            updateOnEmptySelection: true,
        },
        paste: {
            cleanPastedHTML: true,
        },
        autoLink: true,
        keyboardCommands: true,
        placeholder: {
            text: "What's on your mind?"
        }, 
        extensions: {
            'imageDragging': {},
            'tag': new MediumButton({
                label: '<i class="fa fa-tag"></i>',
                start: '`',
                end:   '`',
                action: function(html, mark, parent, base){
                    console.log(base);
                    $('.tagging_list').remove();
                    $('#currentEditor').val(base.id);
                    if(mark){
                        showTagList(html);
                    }
                    return html;  
                },
            })
        }
    });
```

2. Call this in an ajax call: `editor.addElements('.posts'); `

3. Try to do an `editor.getContent(1)` and it gives you the first instance of the editor.

### Versions

- medium-editor: latest version (downloaded on Monday)
- browser: Chrome 54.0.2840.99
- OS: Windows 8.1

**Comment by nmielnik** [comment]
@cbloss when you say "it causes the ID to be off" what do you mean?

There are 2 different concepts I think you're talking about here:
1. instances of the editor
2. elements within the editor

A single instance of the editor can contain multiple elements.  The `.addElements()` method allows you to add new elements into the editor after the editor has already been created.

When you call `.addElements()` you're not creating a new instance of the editor, you're adding a new element to the editor.  The `editor.id` attribute is meant to be unique amongst multiple instances of the MediumEditor object.  So, if you created a new instance of MediumEditor, that new instance would have a new `editor.id` attribute: 

```js
var editor = new MediumEditor('.posts', ...);
console.log(editor.id) // this would be 1
...
// after AJAX call
var editor2 = new MediumEditor('.posts');
console.log(editor2.id) // this would be 2
```

So, can you help clarify what the issue is that you're running into?  As described, I don't think there's a bug here as this is the expected behavior...

**Comment by cbloss** [comment]
Sorry for the delay. I'm going to close this. I think I was misunderstanding what the ID was for. I was able to fix this by pretty much just re-initializing this when a dynamic element was created.

**Comment by ElEmFurt** [comment]
I was able to still reproduce this with the latest code version for elements that are added via ajax after the page has initialized.

As you mentioned the editor has a unique id, however the elements if added via AddElements are duplicated since the code between 6924-6934 in method `createContentEditable(textarea)` run very fast (_using Chrome Version 98.0.4758.102 (Official Build) (64-bit) on windows 8.1_) and hence for two consecutive editor elements it returns the same timestamp and thus on the UI two editor elements get the same id.

**line 6929 ->**
`// Some browsers can move pretty fast, since we're using a timestamp
        // to make a unique-id, ensure that the id is actually unique on the page
`

        while (this.options.ownerDocument.getElementById(uniqueId)) {
            now++;
            uniqueId = 'medium-editor-' + now;
        }`

Also this is happening since the elements are newly added in the array but not yet on the page, and hence the check above fails.

To demonstrate this I did a search on elements array instead of the elements on the page, I added two console statements:
`
        console.log(uniqueId);
        console.log(this.elements.map(data => data.id).indexOf(uniqueId));
`

Here is how it looks

![image](https://user-images.githubusercontent.com/73025802/155872745-db11f9c7-cc43-439c-8d94-642582c1a32e.png)

If you see the last two medium editor element ids they are the same and while all the others returned -1, since they are not in the elements array, the last one returned an actual position since it is a duplicate.

I can only see the fix being as changing the code that checks for uniqueness `this.options.ownerDocument.getElementById(uniqueId)` to something like this `this.elements.map(data => data.id).indexOf(uniqueId) != -1`

What do you think @nmielnik ?

**Comment by ElEmFurt** [comment]
> I was able to still reproduce this with the latest code version for elements that are added via ajax after the page has initialized.
> 
> As you mentioned the editor has a unique id, however the elements if added via AddElements are duplicated since the code between 6924-6934 in method `createContentEditable(textarea)` run very fast (_using Chrome Version 98.0.4758.102 (Official Build) (64-bit) on windows 8.1_) and hence for two consecutive editor elements it returns the same timestamp and thus on the UI two editor elements get the same id.
> 
> **line 6929 ->** `// Some browsers can move pretty fast, since we're using a timestamp // to make a unique-id, ensure that the id is actually unique on the page `
> 
> ```
>     while (this.options.ownerDocument.getElementById(uniqueId)) {
>         now++;
>         uniqueId = 'medium-editor-' + now;
>     }`
> ```
> 
> Also this is happening since the elements are newly added in the array but not yet on the page, and hence the check above fails.
> 
> To demonstrate this I did a search on elements array instead of the elements on the page, I added two console statements: `console.log(uniqueId); console.log(this.elements.map(data => data.id).indexOf(uniqueId));`
> 
> Here is how it looks
> 
> ![image](https://user-images.githubusercontent.com/73025802/155872745-db11f9c7-cc43-439c-8d94-642582c1a32e.png)
> 
> If you see the last two medium editor element ids they are the same and while all the others returned -1, since they are not in the elements array, the last one returned an actual position since it is a duplicate.
> 
> I can only see the fix being as changing the code that checks for uniqueness `this.options.ownerDocument.getElementById(uniqueId)` to something like this `this.elements.map(data => data.id).indexOf(uniqueId) != -1`
> 
> What do you think @nmielnik ?

Forgot to mention, my design adds a row of elements together, and hence the elements as are being processed by your logic are not available in the DOM immediately, and only get added to the DOM at the very end where the whole row is added in a grid with like 3-4 editor elements.

This might be what is causing the bug, however scanning the array in my opinion is more safer, since your elements array always has the latest list versus the DOM on the page.
