### ISSUE TITLE
Typed medium-editor 

### ISSUE THREAD

**Issue by cicada0014** [yabwe/medium-editor#1307]
### Description

Hi, I am a rookie programer. I've just studied for 8 month.  
I use Medium-editor in my project with Angular2/typescript.  um, For Angular2/typescript Users, I wirte some information that I finded.

use '@types ' command.
> npm install @types/medium-editor 
![2017-03-05 5 35 46](https://cloud.githubusercontent.com/assets/22612066/23585770/3a2cf26a-01ca-11e7-8120-bb99b13d04c4.png)
then, you'll use type of medium-editor.    

when I tried to apply custom button, I see that.
![2017-03-05 5 41 26](https://cloud.githubusercontent.com/assets/22612066/23585809/05972394-01cb-11e7-93b2-6456db8665a3.png)

if you fix this, this problem is solved.
/@types/medium-editor/index.d.ts : 97line  buttons string[] type = > object[] type

![2017-03-05 5 45 06](https://cloud.githubusercontent.com/assets/22612066/23585832/7fdad2f4-01cb-11e7-9cb4-3a53fd3f059f.png)

I always thanks for you guys. 
This issue is my first github issue in mylife.
I just wanted to help you with some way.

### Versions

- medium-editor:^5.22.2
- browser: 
- OS: OSX

**Comment by paradite** [comment]
Hi @cicada0014 I think you are spot on with what is wrong with the type definition. It should be `object[]` type.

However, the code with the issue is not in this repo, but at 

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/354cec620daccfa0ad167ba046651fb5fef69e8a/types/medium-editor/index.d.ts

You can submit a PR or issue to that repo to fix this issue.

**Comment by cicada0014** [comment]
Thanks, @paradite  . I migrate this issue for that you commented. And I close this issue.
