### ISSUE TITLE
MediumEditor 2.0

### ISSUE THREAD

**Issue by daviferreira** [yabwe/medium-editor#202]
First, thanks to everyone who contributed so far with this project. It's been really fun for me and I really appreciate it.

I'm going to start developing MediumEditor 2.0 and I am looking for ideas and ways to improve it. Let's use this issue as a brainstorm. This is what I have thought so far.

The medium-editor.js file has now 1300 lines (my bad). It is becoming hard to maintain and, most of all, understand. Also, we have code that are common to all instances of the editor, like the selection handlers, paste handlers, isIE property etc.

It is time to modularize it. Here is the structure i have imagined:
- core.js
- common.js
- util.js
- paste.js
- positioning.js (not sure if we need this one)
- selection.js
- toolbar.js
- button.js
- plugin.js

Button and Plugins should be easy to extend. We need to have a nice API for them. Plugins will be stuff like anchor preview, markdown, image upload, horizontal rule on double enter, paste handler for webapps etc.

I'm also cosindering the use of two external libraries: [bean](https://github.com/fat/bean) for events and [rangy](https://code.google.com/p/rangy/) for selections.

This is it for a kick off. Any thoughts?

/cc @devalnor, @yacomink, @seifsallam, @pixelpony, @websirnik, @orthes

**Comment by antoniobrandao** [comment]
@litera H1 and H3 elements margins are related to CSS? Come on... Did I give the impression I may not be familiar with CSS basics?

It kinda of sounds like including some default CSS is sacrilege for you? You say you're a designer but that sounds like a purist developer's point of view. It's not right. We have to look at this as a product, something that will be out there to help editors and consumers. Not just for devs to admire the code.

What I mean is not about style, but about the dynamics between text elements. Typography dynamics, which were long ago standardised by the Print Industry, but the Internet took ages to catch on (thanks to sites like www.medium.com).

This is an important point to understand: Not all CSS is visual style. Lots of CSS is functional! 

There is visual CSS and behaviour CSS. E.G. Media queries are behaviour, not style. All CSS in responsive design is behaviour, not style. It's visual, but behaviour, not style. Style needs a color, a shape. Otherwise you couldn't use libraries like Rupture.css for responsive design without having your app's visual style changed. But you can.

I'm advocating for some behavioural CSS in this clone, so users can have a good foundation for proper typography behaviour out of the box. Then they can tweak it if needed. And let the rest of the visual styling up to us.

If you think about it, where will you get any sort of typography behaviour from, without CSS? From within JS? That would be a bad practice for sure.

Finally: ALL typography in the internet - and print - if it supposed to be read by anyone - needs a good foundation for proper typography, proper dynamics, if possible following the print industry standards. If you have a P tag, there is no point in NOT creating a margin below, it will be needed anyway. The internet is full with bad typography, without any artificial intelligence, because of the general disregard for what I am advocating. Most typography in the Internet is bad to read, and bad for user conversion. www.medium.com created a new standard and influenced the community precisely because of this. They showed the world how proper typography is done, and how it is in public demand (and thus became so popular).

I challenge anyone reading this to make sure you know, or really study about quality typography in the Internet and Print industry, before judging my idea. Understand the difference between typography dynamics, and general visual style. And then try to understand what exactly makes the artificial intelligence behind www.medium.com's editor so good, and why this clone (the best ever) should have it too!

Cheers

**Comment by antoniobrandao** [comment]
I'm not talking about themes. I think you may not be understanding my point. I'm sorry my explanation is so long and scattered through several comments it may be hard to understand if you don't read the whole conversation.

I advocated for the inclusion of such a foundation - NOT enforcing it. And it's not a theme, it's not "style", but a small set of layout mechanics / artificial intelligence for the text elements within the editor.

To know what I mean, one has to study the artificial intelligence behind www.medium.com's original editor. Go on there, inspect the editor while you fiddle with it and see for yourself. It's brilliant. And it's not a theme!

Is the purpose of a medium-clone just about having a fancy menu that floats above the text we select? In my view there is an artificial intelligence in www.medium.com's editor and it would be great if we could bring some of it into the v2 of this clone.

**Comment by litera** [comment]
@antoniobrandao It's not us, that don't understand your point. Apparently it's you who doesn't explain it very well. What you're referring to is CSS related. If you want us to actually understand what you mean then I suggest you explain by examples. one by one. And with each example provide additional information what parts are CSS and what parts are AI (as you call it - I'd just say programmatic algorithm). I'm having hard time myself understanding what you're referring to and I've read the whole conversation.

**Comment by antoniobrandao** [comment]
I give up.
