### ISSUE TITLE
cyrillic encoding during links paste

### ISSUE THREAD

**Issue by caxopog** [yabwe/medium-editor#291]
Hello

If i insert link with cyrillic symbols (like http://краски.рф)
I've got encoding troubles:
http://gyazo.com/ca9b2b119be979c3cebd55e11206c345

can't find where to fix it in plugin code :(

**Comment by nmielnik** [comment]
Anyone know if this is still an issue?

**Comment by D-side** [comment]
@nmielnik well, **works on Firefox DE**, producing raw cyrillic URLs (not punycode). Since `contenteditable` is not an ancient feature, I assume all supported browsers can handle that just fine.

So either you fixed what was wrong, or Firefox developers have fixed the underlying issue. I'll go find some older versions of Firefox and report my findings.

**Comment by D-side** [comment]
Tested on Firefox 33, works the fine (with same plain cyrillic characters), and it's not even the latest version.

Apparently this is resolved.

**Comment by nmielnik** [comment]
@D-side thanks a ton for taking the time to validate that the issue is resolved, we definitely appreciate it!
