### ISSUE TITLE
Option for completely disabling formatting

### ISSUE THREAD

**Issue by hellocosmin** [yabwe/medium-editor#480]
The way it is right now, if you want only the `contenteditable` functionality, you use the `disableToolbar` option to not show the toolbar. 
The keyboard shortcuts that the browser implements (<kbd>Ctrl+B</kbd>, <kbd>Ctrl+I</kbd>, <kbd>Ctrl+U</kbd>) are still available in this case.

But what if you want to completely prevent any formatting in the `contenteditable` ? 

**Feature request:** would you consider an option that specifies whether these key combinations are allowed or not? Ideally, something that disables the combinations individually (maybe you want bold&italic, but not underline).

Looking forward to hearing your thoughts on this :)

**Comment by nmielnik** [comment]
So currently there is support for listening to <kbd>Ctrl+B</kdb>, <kbd>Ctrl+I</kbd>, and <kbd>Ctrl+U</kbd> so ensure the text becomes Bold, Italic, and Underlined.  We needed this manual code since not all browsers support these shortcuts today.

So the support for this is implemented in `button.js` via the `handleKeydown` method for whatever buttons have a `key` property specified.

The code is already calling `.preventDefault()` and `.stopPropagation()` for key combinations that are supported for each button, so we could do an additional check in there to decide whether we actually follow through and execute the action.  (I'm assuming `.preventDefault()` would prevent the browser from executing bold, italic, or underline, but we may want to make sure this is the case).

Assuming we can implement the behavior easily, the question would be do we want to create a new option for this?  Should we extend the `disableEditing` or `disableToolbar` options to also turn off these keyboard shortcuts?

My vote would be create a new `disableActions` option, which would then be interchangeable with the `disableToolbar` option, where both options do the same thing (no toolbar + no keyboard shortcuts).  This way, people who are using `disableToolbar` can continue to do so, but we have a more clear option to use going forward: `disableActions`.

What do you think?

**Comment by hellocosmin** [comment]
+1 for a `disableActions` option. From a user point of view, I also think it's better to have it separate.

**Comment by nmielnik** [comment]
We should implement a solution for #180 as part of this effort.

**Comment by litera** [comment]
Why not use a styles `textarea` in such case when you don't allow any text styling and only need to enter multi-line text? Why overcomplicate your life for later maintenance headaches?

**Comment by hellocosmin** [comment]
Because that doesn't apply in any situation. For example, I am using ME to create an email template builder, where you work directly on the template itself. So a textarea is out of the question in that case. Same applies in any situation where you're offering the user the chance to edit existing HTML. A textarea would actually over-complicate things in this case.

**Comment by phiggins42** [comment]
Note, you could disable the key actions yourself, in a pinch. Without having to know which ones have keys:

```
var buttons = MediumEditor.statics.ButtonsData; // i think? def 4.1, maybe earlier
for(var i in buttons){
   delete buttions[i].key;
}
```

now your mediumeditor won't have any builtin buttons that define keys. (`disableActions` would be easy to implement, too, just don't bother looking for a .key during Button init) but above should work in a pinch?

**Comment by litera** [comment]
@hellocosmin I would like to discuss your use cases a bit further because I don't really get your point.

**Email template**: So if one is editing an email template do you want HTML styling or not? If yes, then of course ME, but if not, textarea should do just fine.

**Edit content**: Why would you want to disable styling when editing HTML-styled content? Suppose user want to delete part of the bolded passage and then unbold it because part that they deleted remove the need for stressing the passage... Why would you want to disable styles in this case? What if they wanted to change a header? They'd delete existing one but then they wouldn't have any way to make new header look like header?

**Comment by hellocosmin** [comment]
@litera : @phiggins42 pretty much summed it up in the last paragraph.

What I am suggesting, is an <em>option</em> that would allow for this. In some cases, like mine, you have full control over the content users will be editing with the help of ME. In this case, I need to be able to completely stop users from formatting the content: if it's formatted, they won't be able to change it and if it's not formatted, it needs to stay that way.

Think about the fact that some ME users implement this wonderful editor in environments where they have strict design requirements that need to be followed and enforced onto the final users, so that those final users don't get any familiar way of screwing with the formatting.

**Comment by hernan124** [comment]
+1

**Comment by nmielnik** [comment]
This seems like a good candidate for a 'mode' as proposed in #92

**Comment by litera** [comment]
@hellocosmin I still don't get it. Are you trying to **completely** disable formatting (like no HTML at all, not even `<p>` elements but rather just `\n` newlines) or are you trying just to disable some of the formatting (bold, italic, lists etc?).

Because if it's first (no formatting whatsoever) then a textarea with specific styling would do the trick. You can style the way it displays text (family, size, weight, leading/line-height etc.etc). You can restyle its default visual design to remove its borders, resize handles etc etc... And you can also add a small simple script that will make it auto-grow in height according to its content which is the same as an editable DIV...

So. Which formatting disability are you after?

**Comment by nmielnik** [comment]
A workaround for this appears to be a combination of disabling the toolbar (`{toolbar: false}`) and implementing a custom keyboard extension as described in #903
