### ISSUE TITLE
Toolbar options not working properly?

### ISSUE THREAD

**Issue by nzifnab** [yabwe/medium-editor#696]
I'm trying to do the following:

    editor = new MediumEditor('.editable', {
      toolbar: {
        buttons: ["bold", "italic", "underline", "h2"]
      }
    })

But this doesn't seem to be doing anything. The toolbar is still getting "bold", "italic", "underline", "anchor", "h1", "h2", and "quote" (Even though the defaults are supposed to be "h2", and "h3", not "h1", and "h2"?)

When I make the `buttons` options top-level and take it out of the toolbar options like so, this works:

    editor = new MediumEditor('.editable', {
      buttons: ["bold", "italic", "underline"]
    })

HOWEVER, I cannot add "h2", "h3", or any other `heading` buttons to this because if I do, I get the javascript error:

    Uncaught TypeError: Cannot read property 'getButton' of undefined

I am using the 4.12.5 release found here: https://github.com/yabwe/medium-editor/releases

Am I doing something wrong? Is the documentation incorrect or am I supposed to put the `buttons` array outside of the toolbar options?

Edit:  I just did some more checks, ALL of the button options work for me with latter format (not nested within the `toolbar` options) except for the `heading` buttons.

Edit 2:  And doing the options `{toolbar: false}` does not appear to do anything either.

Edit 3: Here's a jsfiddle with these issues in practice: http://jsfiddle.net/nzifnab/e9LLp93u/1/

**Comment by j0k3r** [comment]
We might have mixed both documentation for v4 and v5 at some point.
The fact is the current documentation is for the v5 release (if you look in the master atm). If you take a look at the [README from the 4.12.x branch](https://github.com/yabwe/medium-editor/blob/4.12.x/README.md) you'll see the _documentation_ for the v4.

That's why your taking new thing from the v5 (nested buttons in toolbar) and apply them in the v4.

 - `h1` -> `h6` buttons have been introduced in the v5 release.
 - toolbar is a dedicated extension in the v5

Using the v4, you can achieve what you want with:

```js
new MediumEditor('.editable', {
  buttons: ["bold", "italic", "underline", "header2"],
});
```

Default `header2` button will display a `h2` button in the toolbar but will create a `h4`. If you want to create a `h2` you should update the `secondHeader` option:

```js
new MediumEditor('.editable', {
    buttons: ["bold", "italic", "underline", "header2"],
    secondHeader: 'h2'
});
```

Sorry if you get confused with doc. We are about to release v5.0.0 in few days and are trying to get everything ready for it (documentation, readme, wiki, etc ...)

**Comment by nzifnab** [comment]
Ohhhh. Thanks a lot for the clarification. Is it "safe" so-to-speak, for me to use the 5.x release candidate? Probably a good idea to be as up-to-date as possible since I'm only just now building a feature that will use this library.

**Comment by j0k3r** [comment]
It's completely safe to use v5 since we [released it yesterday](https://yabwe.github.io/v5-is-out.html)! Also the document in the wiki is now clearly splitted for the v5 & v4.
