### ISSUE TITLE
May I implement a filter / parser in selection module ?

### ISSUE THREAD

**Issue by be-next-hotdog** [yabwe/medium-editor#699]
Hi guys, come again with another question,
what should I do to extend the selection ? Directly dev within or with MediumEditor.selection ? 
Needy for cleaning the illegal / special charactors in the selected text (i.e; slash, space etc)

**Comment by be-next-hotdog** [comment]
sorry for the wrong topic...

**Comment by nmielnik** [comment]
You can definitely add helper methods into `selection.js`, but we'll only want to add methods like this if they will be leveraged by the core MediumEditor functionality.  If it's something that is specific only to your code or your extension, it would be best to keep it there until it can be reused by other code.

**Comment by be-next-hotdog** [comment]
I know how really annoying it is but I still wanna ask this annoying question : the cleanest way to extend selection ? 
PS : XD, its time to document Medium editor ?

**Comment by j0k3r** [comment]
You kidding? https://github.com/yabwe/medium-editor/wiki

**Comment by be-next-hotdog** [comment]
Yes & No, did read the wiki page but I wish to comment what we dev directly in code, for instance the angular.

**Comment by be-next-hotdog** [comment]
BTW, still not found how to trim the select text before turning that in bold or in italic ?

**Comment by be-next-hotdog** [comment]
No one knows ?

**Comment by nmielnik** [comment]
I'm am not aware of a simple way to trim text within html elements, since the beginning or ending spaces could be within text nodes at any level within the DOM. For example:

```html
<p>
  <i>[space]</i>
  <b>my bold, <i>and italic</i> text</b>
  <i>[space]</i>
</p>
```

Depending on where your selection starts and begins, trimming this text could be a bit complicated.

What you could try to do is find the first text node within the selection, and iterate over all text nodes until you hit something that contains non-whitespace characters, removing all *leading* whitespace along the way.  Then find the last text node within the selection, and iterate backwards over text nodes until you hit something that contains non-whitespace characters, removing all *trailing* whitespace along the way.

You could use something like the built-in [TreeWalker](https://developer.mozilla.org/en-US/docs/Web/API/TreeWalker) object to achieve iterating over text-nodes in DOM order.

**Comment by be-next-hotdog** [comment]
; ) 
Grateful for advices but I just wanna know where should I modify in order to trim selected text before "bold" it ? tried to modify little in core/toolbar but still doesnt work for me.

**Comment by be-next-hotdog** [comment]
Hacked selection object for now, still await for a better solution.
