### ISSUE TITLE
Is there a recommended way to add a (copy of a) button?

### ISSUE THREAD

**Issue by csarven** [yabwe/medium-editor#705]
I am currently observing different ways of adding a button to the toolbar. Is there a best-practice in place?

For instance, instead of using the built in default button for bold which outputs `<b>`, is it possible to use `<strong>`, meanwhile keeping everything else the same? The obvious process for some like this is to create a new extension, however, I find the process to replicate common handlers e.g., handleClick tedious. Is there a way to add a new button for `strong` which can be a copy of `bold` with the difference being on the output tag? I do not wish to override `bold`.

**Comment by csarven** [comment]
There is an issue #310 related to the example above.

**Comment by nmielnik** [comment]
So the built-in buttons are built around using `document.exeCommand()`.  `document.execCommand('bold')` produces `<strong>` tags in IE, but `<b>` tags in Chrome, Safari, and Firefox. Thus, if you only wanted to make minor modifications to these buttons you would have to override at least `handleClick()`.  We have support for overriding parts of built-in buttons like this:

```js
new MediumEditor('.editor', {
  toolbar: {
    buttons: ['italic',
      'underline',
      {
        name: 'bold',
        contentDefault: '<strong>ST</strong>',
        handleClick: function (event) {
          // your custom code for wrapping selection in <strong>
        }
      }
    ]
  }
});
```

That would allow you to make just minor changes to the bold button, but you would be overriding it.  If you wanted to add a new button that didn't replace 'bold', you would need to create a new Button extension.

```js
var StrongButton = MediumEditor.extensions.button.extend({
  name: 'strong',
  contentDefault: '<strong>ST</strong>',
  action: 'strong',
  tagNames: ['strong'],
  handleClick: function (event) {
    // you custom code for wrapping selection in <strong>
  }
});

new MediumEditor('.editor', {
  toolbar: {
    buttons: ['italic', 'underline', 'strong']
  },
  extensions: {
    'strong': new StrongButton()
  }
});
```

Those extra options (`action`, `tagNames`) are overrides to leveraging the built-in button support for your custom button.  Either way, if you want to always produce a `<strong>` tag, you'll have to change what happens when the button executes (which is defined in `handleClick()`)
