### ISSUE TITLE
One click to open toolbar

### ISSUE THREAD

**Issue by courgette** [yabwe/medium-editor#717]
Hi,
It's possible to open toolbar with one click ?
Thanks

**Comment by j0k3r** [comment]
Which case do you want to achieve?
Where should you click to open it?

We need more information if you want a proper answer :smile:

**Comment by courgette** [comment]
Actually, on a element, i have to double click on this element to access to the toolbar and edit my element. So, i want to do the same thing, but with one click.

**Comment by j0k3r** [comment]
You have to double click because you need to select some texts before taking any actions with the toolbar. In fact, the toolbar is fired as soon as you select some texts.

What you are looking for is put your cursor in some random text, then the toolbar is fired but what should happen if you hit the bold button for example? Which should we put in bold? Only the word around your cursor? The whole line?

**Comment by courgette** [comment]
Ok, right !
it's logic, thanks for your answer !

**Comment by cristianst** [comment]
I have a little hack for that :)

**Comment by iagopiimenta** [comment]
I need it to work with images. Add actions to change, crop and so on. Double click is unusual and practical to do so. Do you have plans for this?

**Comment by nmielnik** [comment]
@iagopiimenta there aren't plans for this, though this sounds like an interesting enhancement that could be enabled via an configuration option (allow for selecting images on a single click, which should show the toolbar).

Would you mind opening a separate issue with this request (or even taking a crack at a PR to add the feature :wink:)?

**Comment by jamespacileo** [comment]
It would be useful if some buttons are related to the line or parent element, and not the text.
