### ISSUE TITLE
Reset Medium editor.

### ISSUE THREAD

**Issue by DylanPiercey** [yabwe/medium-editor#719]
It would be nice if the editor (when tied to a textarea) automatically reset when the textarea's for resets.

Currently when I reset my forms using ```form.reset()``` everything gets reset (including the textarea) but not the medium editor.

**Comment by nmielnik** [comment]
From looking into this a bit, there doesn't seem to be a way to know when the textarea has been cleared as a result of doing a `form.reset()`.  

So, in order to do this, we'd need to attempt to detect if the existing `<textarea>` is within a form, and if it is, attach to the `reset` event of the `<form>` element itself and manually clear the editor. 

For example, we could add some code into the [`initElements()`](https://github.com/yabwe/medium-editor/blob/master/src/js/core.js#L330) method to do something like:

```js
function initElements() {
    this.elements.forEach(function (element, index) {
        // ...

        var form = null,
            node = textarea.parentElement;
        // Find if the textarea is inside a form
        while (node) {
            if (node.nodeName.toLowerCase() === 'form')  {
                form = node;
                break;
            }
            node = node.parentElement;
        }
        // If we found a form, attach to onreset so we can 'reset' the <div>
        if (form) {
            var editable = element;
            // Store the original value so we can reset back to it
            editable.setAttribute('data-orig-value', editable.innerHTML);
            this.on(form, 'reset', function (event) {
                editable.innerHTML = editable.getAttribute('data-orig-value');
            });
        }

        // ...
    }, this);
}
```

This is just some code I coded up here, so I'm not sure if it will work as-is, but it should be a good way to get started...

This could be a simple and easy way to have a first contribution :smile: Anyone wanna give it a shot?

**Comment by DylanPiercey** [comment]
Not sure what the browser support is, but inputs within the form are given a #form attribute.

Rather than looping up the parent nodes until you find a form you should be able to just check for

```javascript
textarea.form; // -> <Form/>
```

**Comment by nmielnik** [comment]
@DylanPiercey finally got around to opening a PR for this (#1104)
