### ISSUE TITLE
Hide toolbar when using an extension

### ISSUE THREAD

**Issue by sebastiannm** [yabwe/medium-editor#720]
I have been trying to create my first extension but I'm stuck at the part where I should hide the toolbar as the anchor extensions does.

I'm using this code from inside the extension after clicking the actionButton:

```
var toolbar = this.base.getExtensionByName('toolbar')
if (toolbar) {
      toolbar. hideToolbarDefaultActions()
}

```

For some reason this only hides my custom buttons and doesn't hide the toolbar. How should I do?

**Comment by nmielnik** [comment]
The purpose of the `hideToolbarDefaultActions()` method is so something like the anchor extension can hide the buttons inside the toolbar, and display an input field inside the toolbar.  It doesn't want the entire toolbar to hide itself.

In what case are you trying to hide the entire toolbar?  I just want to double-check that this is the functionality you need, because the toolbar may not stay hidden for long, and I haven't worked with code that manually hides the toolbar to see if there are any weird bugs.

So, to answer your question, you can do this from within your extension:

```js
var toolbar = this.base.getExtensionByName('toolbar');
if (toolbar) {
  toolbar.hideToolbar();
}
```

If you have any issues, let us know what you're attempting to achieve to see if there might be a more common way to accomplish the same thing.

**Comment by sebastiannm** [comment]
Thank you for your answer.

I did try that but the only behavior I get is the editor hiding my default buttons. Notice the image icon at the right.

Before: 

![screen shot 2015-07-02 at 5 19 56 pm](https://cloud.githubusercontent.com/assets/1763632/8488182/c7e50cc4-20de-11e5-8fcd-3f597ef0c75a.png)

After:

![screen shot 2015-07-02 at 5 20 02 pm](https://cloud.githubusercontent.com/assets/1763632/8488184/ccf65a42-20de-11e5-9a6a-1b4b4ec4156b.png)

**Comment by nmielnik** [comment]
Make sure you're calling `hideToolbar()` and not `hideToolbarDefaultActions()`.

Based on the screenshots you're showing, I'm thinking there's something else going on here (there might be 2 toolbars being displayed, and when you hide one the other one becomes visible).

Can you share the code or create a JSFiddle which shows the issue?  Can you check to see if you're instantiating multiple version of MediumEditor?  There shouldn't be any way to hide just one specific button, unless you've done something with the css or something unique in your specific code.

**Comment by sebastiannm** [comment]
Here I created a Fiddle:

https://jsfiddle.net/sebastiannm/tcg6pf8r/

**Comment by sebastiannm** [comment]
I found the issue, It happen when using the wrapper for angular.
Thanks

**Comment by nmielnik** [comment]
@sebastiannm Thanks for posting the JSFiddle, I was able to find a few things that would definitely help you, and I've posted an updated JSFiddle here: https://jsfiddle.net/tcg6pf8r/3/

* You'll want to extend from `MediumEditor.extensions.form` instead of `MediumEditor.Extension`.  This form extension also derives from the button extension, so you'll get a bunch of things for free:
  * Creates the button using the 'contentDefault' property, and attaches the click handler
  * Gives you access to some helper methods like `this.hideToolbarDefaultActions()`
  * Defines the core methods / properties you need for a form extension
* Take a look at the [Form Extension](https://github.com/yabwe/medium-editor/blob/master/src/js/extensions/form.js) code which defines the basic functionality for forms.  Also, look at the [Button Extension](https://github.com/yabwe/medium-editor/blob/master/src/js/extensions/button.js) code, which is additional functionality that you can work with (since form extension extends the button extension).

Apologies if this stuff is confusing, I'm still trying to work through the documentation.

As you get closer to finished, would you be willing to share your final code?  I would love to use something like what you're making as a step-by-step guide on how to create a form extension, so it would be awesome if I could add your code into our Wiki.  Would you be ok with that?

**Comment by sebastiannm** [comment]
Thanks

Of course, I'm almost done with it, I would love to share it when done

**Comment by sebastiannm** [comment]
I come here with the example.

After clicking on the button, it will fetch images from flickr and show a grid that can be selected.

https://jsfiddle.net/sebastiannm/tcg6pf8r/

**Comment by nmielnik** [comment]
Thanks a ton!
