### ISSUE TITLE
Do not change classes in anchor

### ISSUE THREAD

**Issue by l2aelba** [yabwe/medium-editor#726]
Is it possible to prevent removing classes when edit link ?

**Example :**

`<a href="#" class="one two three">My button</a>`

Those classes will stay when edited link.

Any option I missing ? or any idea ? Thanks.

**Comment by nmielnik** [comment]
I'm not sure if this is quite what you're looking for, but there's always the [`customClassOption`](https://github.com/yabwe/medium-editor/wiki/Options#customclassoption) which allows the user to choose whether to have a specific class(es) on the link that they create.

Otherwise, you may have to override the anchor extension or the anchor-preview extension in order to inspect the classes before the link is edited, and make sure they are added back on to a created link.

**Comment by l2aelba** [comment]
@nmielnik ,Thanks so much, but some bugs https://github.com/yabwe/medium-editor/issues/738

**Comment by nmielnik** [comment]
Yeah, there is something odd going on with the link editing.  Until I get time to investigate, hopefully someone else can see what's causing the issue.

Thanks a ton for opening these issues!
