### ISSUE TITLE
Modifying extension buttons seems to have no effect

### ISSUE THREAD

**Issue by tanelkarp** [yabwe/medium-editor#728]
Hi! 
I'm using the Medium Editor together with the tables extension and Dashicons for the toolbar buttons. For some reason, I can't modify the "table" button, it just states "tbl" and doesn't apply the options I've set. Is this expected behaviour, a bug or an error on my end? 

Here's the code:
```javascript
toolbar: {
	buttons: [
		{
			name: 'bold',
			aria: 'bold text',
			contentDefault: '<span class="dashicons dashicons-editor-bold"></span>'
		},
		…
		{
			name: 'table',
			aria: 'add table',
			contentDefault: '<span class="dashicons dashicons-grid-view"></span>'
		}
	]
},
extensions: {
	'table': new MediumEditorTable()
}
```

And here's what I'm seeing, just "tbl" for the button and no hover text:
![image](https://cloud.githubusercontent.com/assets/2767873/8708803/e761e848-2b46-11e5-833b-2fcf29813d60.png)

**Comment by nmielnik** [comment]
The method in which you're overriding the buttons (`toolbar.buttons` option) allows you to override the properties of the built-in buttons for MediumEditor.  However, `MediumEditorTable` is not a built-in button.

Since you're passing an actual extension object in via the `extensions` option, the custom extension itself is in charge or setting the content of the button it generates. Thus, if you want to change the content of the button for `MediumEditorTable`, you'll have to modify the internal code it uses to generate the button.  You can see the function that does this in the [MediumEditorTable source code](https://github.com/yabwe/medium-editor-tables/blob/master/src/js/plugin.js#L68-72).

An example of a hacky way to override this `_createButtonElement` method would be something like this:

```js
MediumEditorTable.prototype._createButtonElement = function () {
    this.button = document.createElement('button');
    this.button.className = 'medium-editor-action';
    this.button.innerHTML = '<span class="dashicons dashicons-grid-view"></span>';
    this.button.setAttribute('aria-label', 'add table');
    this.button.setAttribute('title', 'add table');
}
```

Thus, when you pass in `new MediumEditorTable()` via extensions, it will now generate a button with the content you want.  You could also consider creating your own custom extension that derives from the `MediumEditorTable` extension, and overrides whatever methods you want, ie the `_createButtonElement` method.

Once you fix this, you'll still need to pass an argument into the `toolbar.buttons` option, since this is what tells MediumEditor to display a button for a specified extension.  So you'll still need to do this:

```js
toolbar: {
	buttons: [
		{
			name: 'bold',
			aria: 'bold text',
			contentDefault: '<span class="dashicons dashicons-editor-bold"></span>'
		},
		…
		'table'
	]
}
```

Passing the string 'table' tells MediumEditor that the extension with the name 'table' has a button which should be displayed in the toolbar.  Since you can't override the properties of a custom extension via the `toolbar.buttons` option, you only need to pass a string here (and not an object).

Hope that helps.

**Comment by daviferreira** [comment]
But I think it's a nice feature to add, to override extensions buttons.

**Comment by nmielnik** [comment]
@daviferreira perhaps the table-extension could be updated to allow for this overriding as well?

**Comment by daviferreira** [comment]
https://github.com/yabwe/medium-editor-tables/commit/da46c9f193ce3ac07ce622c75e25f580b1bd2b0e

**Comment by daviferreira** [comment]
You can do something like:

```
  extensions: {
      table: new MediumEditorTable({
        button: '<span>test label</span>'
      })
    }
```

No sure about to do with aria, name and attrs, because then we will end up rewriting the button method on the extension. What do you say, @nmielnik?

**Comment by nmielnik** [comment]
Thanks to @daviferreira now you can override the button labels the same way you would override them for MediumEditor default buttons:

```js
extensions: {
    table: new MediumEditorTable({
        contentDefault: '<span>Custom Label</span>',
        contentFA: '<i class="fa fa-table"></i>'
    })
}
```

**Comment by annayafi** [comment]
Since then, you added a prototype for creating a custom button. But this one still gets a special treatment , and the options are not being built like "aria" or whatever can't be passed in the buttons array (line 7298) : 
 ```
  addBuiltInExtension: function (name, opts) {
            var extension = this.getExtensionByName(name),
                merged;
            **if (extension) {
                return extension;
            }**
```

but for MediumEditor.extensions.button. prototype, we could expect this one to work the same as the built in buttons.

**Comment by annayafi** [comment]
Since there's a prototype for creating a custom button and deriving from button extensions, we could expect the options being built the same way the built-in buttons are. But any extension still gets a special treatment , and the options are not being built like "aria" or whatever can't be passed in the buttons array (line 7298) :

  addBuiltInExtension: function (name, opts) {
            var extension = this.getExtensionByName(name),
                merged;
            **if (extension) {
                return extension;
            }**
I think that for MediumEditor.extensions.button. prototype, we could expect that their options were built the same way as the base button. So maybe, the code could test if it's an extension not deriving from button, and still build the options for all buttons object.
