### ISSUE TITLE
onchange doesn't seem to work as expected

### ISSUE THREAD

**Issue by adrianopolis** [yabwe/medium-editor#731]
If I append some code to my target. I see my images/videos etc appear just fine in the editor but when I save my data and then come back to edit, it's gone. Yet if I do indeed add a space or some other text etc... along with my image,video or whatever else I have appended it works as expected. Any advice or fix to have it recognize my append and trigger the onchange to save the data as if it were a keypress? Example:
                    var image_tag = "image tag markup here...";
                    $(target).append(image_tag);

**Comment by nmielnik** [comment]
I'm assuming you're talking about the custom `editableInput` event?

Either way, as long as you're using subscribe to attach your event handler, you can always manually trigger the event:

```js
// editor is an instance of MediumEditor
editor.subscribe('editableInput', function (event, editable) {
    // your custom save code
});
...
var image_tag = 'image tag markup here...';
$(target).append(image_tag);
editor.trigger('editableInput', {}, target);
```

There is an issue #405 which talks about being able to programmatically change the content in editor elements, it seems like when we implement that change we'd also like it to manually trigger the `editableInput` event as well.

Does that give you a workaround?  I'm guessing you could always manually call your event handler when you append the element as well, although I could see why that wouldn't be ideal.

**Comment by adrianopolis** [comment]
Hi, thanks for the responses. I've replaced the alert("test); with other stuff just to test... like a body click event but it still won't update. I'm probably missing something?
<pre>    
    var editor = new MediumEditor('.editable', { ... });
    editor.subscribe('editableInput', function (event, editable) {
        alert("test");
    });

    $( ".editable" ).focus(function(e) {
        ... my custom stuff is here...
        // Custom Media Image Form
        $( "#media_image" ).on( "click", function() {
            ... my custom code for pulling up a form...
            // Here is where I am taking the code and hoping to append the image and trigger an update
            $( "#save_media" ).on( "click", function() {
                var media_value = $("#media_form_input").val();
                if (media_value.length > 0) {
                    var image_tag = "<img src='" + media_value + "'>";
                    $(target).focus();
                    $(target).append(image_tag);
                    editor.trigger('editableInput', {}, target);
                }
            });
        });
    }
</pre>

**Comment by nmielnik** [comment]
Some thoughts/suggestions:

1. After you call `editor.subscribe('editableInput', function (event, editable) { ... });` did you make sure then when you type inside the editor that the event listener is triggered?  I'm not sure when your code it running, but it's possible that the editable element doesn't exist in the DOM yet when you try to initialize MediumEditor.  Just make sure that the 'editableInput' event listener is being attached correctly.
2. Attaching to the focus event of the editor may be problematic.  MediumEditor attempts to mimic the 'focus' event in a more consistent way (taking into account things like the toolbar).  Try using `editor.subscribe('focus', ...)` instead of `$(".editable").focus(...)`.
3. Confirm that the call to `editor.trigger()` is actually happening (either via a debugger or console log, or something).  If there's some way that `editor.trigger('editableInput')` is actually getting called, and the handler you passed in `editor.subscribe('editableInput')` is not running, there is something else going on here where the editor might be getting destroyed, or the editor reference you're attaching to is difference than the editor instance you're triggering.

Let me know if any of these things yield any helpful information.

**Comment by adrianopolis** [comment]
Thanks for all your helpful feedback and I will work on more of your suggestions however for now as a quick fix I wanted to share our manual solution in case anyone else has similar needs:
We are running this on our submit:
<pre>
        $('textarea.medium-editor-hidden').each(function(index, element) {
            var editable_content = $(element).parent('fieldset').find('div.editable').html();
            $(element).val(editable_content);
        });
</pre>

**Comment by nmielnik** [comment]
ahhh, you're using a `<textarea>` right?  Make sure that you're appending the image to the `<div>` that MediumEditor is creating and not the original `<textarea>` element that was on the page.

MediumEditor doesn't monitor any actions or events on `<textarea>` elements, it only monitors events on the `<div>` element that is created and sync'd up with the original `<textarea>`

**Comment by adrianopolis** [comment]
Awesome thanks!
