### ISSUE TITLE
Using medium-editor to edit titles and descriptions

### ISSUE THREAD

**Issue by scripting** [yabwe/medium-editor#737]
I have medium-editor working to edit the body of a document, but I also want to use it to edit the title and description. I'm working in a small testbed.

http://myword.io/testing/mediumeditor2.html

It's not working very well I think because medium-editor is wrapping the text in a &lt;p>.

Is this not a good way to use medium-editor, or is there some way to turn the automatic addition of &lt;p> elements off. Thanks in advance for any help. ;-)

**Comment by nmielnik** [comment]
You can disable the user hitting `return` via some options, so that could potentially help you prevent the user from adding additional newlines.   However, my guess is that the `<p>` will still end up getting inserted, this is particularly to help make things consistent across various browsers.

You can try instantiating one instance of MediumEditor for the title and description areas, and another instance for the body.

For the instance that you create for title and description you can try using the [`disableReturn`](https://github.com/yabwe/medium-editor/blob/master/OPTIONS.md#disablereturn) option, or maybe the [`disableDoubleReturn`](https://github.com/yabwe/medium-editor/blob/master/OPTIONS.md#disabledoublereturn) option.  So something like:

```js
var editor = new MediumEditor('.title, .description', {
    disableReturn: true
});
```

If the `<p>` is still getting added, you could potentially just strip the surrounding `<p>` when you store it locally, though I know that's a big hacky.  

Otherwise, there isn't any logic to prevent the `<p>` from getting added, as at least some browsers will add this automatically.  If an option to prevent wrapping `<p>` tags was added, it would have to monitor changes to the editor and unwrap the `<p>` as soon as it saw it...

**Comment by scripting** [comment]
Thanks for the advice. 

Thanks for the quick response. 

Adding disableReturn definitely helps.

I did consider stripping out the &lt;p>s, but decided at least for now not to do it. I could easily see that causing breakage down the line. 

The current performance isn't actually all that bad. There is some jumpiness, when you click and start typing, the text slides down a bit. I really want to get that kind of stuff out of there, because the editing experience has to be perfect to get people to use the editor instead of Medium&trade; ;-)

Thanks for the help. If anyone has other ideas, I'd love to hear them. I want to get this as close to perfect as possible.

**Comment by scripting** [comment]
A related question -- what determines the height of the caret?

It's way taller than the text. 

Here's a screen shot that illustrates.

![image](https://cloud.githubusercontent.com/assets/1686843/8813166/5188fc7a-2fcf-11e5-892f-e0a6b3f12117.png)

**Comment by daviferreira** [comment]
Maybe it's because of the custom font you are using, I don't know. But I believe font-size is what determines the caret's height.

**Comment by scripting** [comment]
David, that's a very interesting theory. 

I tried an experiment, and commented out the font-family and font-size styles in the demo app and took a screen shot below (as with the previous shot, it's blown up to make the caret size more visible).

It appears the caret is still too tall. So I don't think it's the font, because this is using the font choices of medium-editor.

<img width="462" alt="caret2" src="https://cloud.githubusercontent.com/assets/1686843/8824746/a72ef2f2-3046-11e5-8203-ea45c451908f.png">

I've saved a snapshot of this version of the editor here.

http://myword.io/testing/mediumeditornofont.html

**Comment by nmielnik** [comment]
Could it be `line-height` that controls the cursor height?

**Comment by scripting** [comment]
Thank you all for the help earlier this week. I've been able to complete the project, knock wood, and it's now released.

http://myword.io/editor/

Here's a document produced by MWE.

http://myword.io/users/davewiner/essays/045.html

It includes an introduction for the people in the medium-editor community.

Thanks again! :-)

**Comment by daviferreira** [comment]
Awesome stuff :+1:

**Comment by nmielnik** [comment]
Congrats on the project, and thanks for the kind words @scripting !  Hopefully we can keep the editor evolving and active!

**Comment by scripting** [comment]
Nate it looks really good. The most important part was there were people here, answering questions and improving the product. 

Hopefully we can move this stuff into all the nooks and crannies it belongs in. ;-)

**Comment by injectless** [comment]
I'm sorry for revive this, but..
@scripting what font did you use in the first image you share it?
it's amazingly beautiful
