### ISSUE TITLE
NS_ERROR_FAILURE Firefox

### ISSUE THREAD

**Issue by erickbelfy** [yabwe/medium-editor#749]
Following #354 i can't use `orderedlist` and `unorderedlist` list using firefox. Using minified version the error raises on line 5706 `return this.options.ownerDocument.execCommand(action, false, null);`

**Comment by daviferreira** [comment]
Could you provide a fiddle? Can't reproduce it.

**Comment by erickbelfy** [comment]
This is my markup
```
<div data-medium-focused="true" data-placeholder="Type your text" medium-editor-index="0" aria-multiline="true" role="textbox" data-medium-editor-element="true" spellcheck="true" class="rich-text" data-type="string" data-field="content" data-options="rich-text" contenteditable="false">
      
      
      
      <p>With young and dynamic teams, daily life at the company is friendly! The successes and other moments for sharing between employees, like the sporting challenges in which the teams participate, all constitute opportunities to unite the teams around a real spirit of enterprise.</p>
    
    
    
    </div>
```

also my configuration 

```
        var stringTypes = $(content.find('* [data-options="rich-text"]'));
        new MediumEditor(stringTypes, {toolbar:{ buttons: ['bold', 'italic', 'orderedlist' ,'unorderedlist'] }});

```

My firefox version is `39.0` i am also using yosemite OSX

**Comment by erickbelfy** [comment]
Maybe a point we need to consider is. My initial status of `contenteditable` attribute is `false` instead of `true` i need to toggle that property, using some code. When i focus out of the target area i change `contenteditable=true` to `contenteditable=false` and i think the library are trying to add a new element inside of that markup using `contenteditable=false`

**Comment by nmielnik** [comment]
so if you are toggling `contenteditable` when the element triggers the 'blur' event, you will definitely run into issues with firefox.  Firefox throws this type of exception whenever you try to call `document.execCommand()` and it thinks the selection or editor is in an invalid state.

Since you're listening to the `blur` event, this event can get triggered whenever you click on the toolbar, since focus is lost by doing this in some cases.

Instead of attaching to `blur` manually, try attaching to the custom `blur` event the MediumEditor triggers.  This event accounts for when the user clicks on the toolbar, or even the anchor-preview, and only trigger when the user has actually interacted outside of the editor:

```js
var editor = new MediumEditor(/* options */);
editor.subscribe('blur', function (event, editable) {
    // your 'blur' handling logic here
});
```

In case you were wondering, there's also a custom `focus` event that you can attach to, though I'm not sure when you're triggering your code which sets `contenteditable` back to `true`

**Comment by daviferreira** [comment]
I believe `stringTypes` is a jQuery object and not a DOM element, or am I mistaken?

**Comment by erickbelfy** [comment]
thanks @nmielnik and @daviferreira the above suggestions makes total sense, i haven't checked at docs that we have support to attach events on medium editor, it really good, helps me a lot! :+1: 

Closing.

**Comment by milossh** [comment]
I get the same error now with latest firefox and medium-editor 4.12.12
