### ISSUE TITLE
Dynamically add new elements to the editor after init

### ISSUE THREAD

**Issue by alpeshgaglani** [yabwe/medium-editor#779]
Hi,
I have a requirement that necessitates adding new elements to DOM, and I'm trying to figure out how to make the editor aware that it has to start monitoring the newly added element. 
Up until a couple versions ago, the following used to work:
```js
editor = new MediumEditor(elementsToMonitor, options);
// a little bit later, newElement is added as a child 
// of one of the elements in elementsToMonitor.
newElement.on('click', myFunction);
elementsToMonitor.push(newElement);
editor.deactivate();
editor = new MediumEditor(elementsToMonitor, options);
```

However, with the latest version, the destroy function *replaces* the html in order to fix a bug with spell-check. This causes all of my own event handlers to stop firing. 
The only way, it seems to me, to retain my event handlers, is to not call destroy, but have a method on the editor to add/remove elements being monitored. Is this possible?

**Comment by nmielnik** [comment]
So, there would need to be a large amount of work in order to expose a method for adding additional elements on the fly.  This is particularly challenging since the extensions will also care about another element being added in, and would thus have to also implement functionality for handling new elements being added.

So, I'm assuming you have the `spellCheck` option set to `true`?  Besides setting the option to `false`, you can add an additional option, such that when it's set to true, it won't reset the innerHTML when calling `destroy()`.  Something like, `disableHTMLResetOnDestroy`?

**Comment by alpeshgaglani** [comment]
For now, spellcheck:false fixes my issue. However, I do want spell check feature. Your suggestion sounds like it would work (i.e. expose an option to not clobber innerHTML)

**Comment by nmielnik** [comment]
Would you be interested in adding in the option to make sure it fixes your case?

**Comment by alpeshgaglani** [comment]
I have a deadline coming up this week, but I can get to it by EOW?

**Comment by nmielnik** [comment]
yeah sure, no rush :wink: I look forward to the PR!

**Comment by nmielnik** [comment]
As of version 5.17.0 there is now officially support for adding/removing elements dynamically to an already existing instance of medium-editor!
