### ISSUE TITLE
Context-aware toolbar

### ISSUE THREAD

**Issue by csarven** [yabwe/medium-editor#797]
Is there a way to trigger/display the contents of a toolbar based on context? For instance, a way to show/hide certain buttons depending on the user selection or where the caret happens to be in the document.

This is related to #668 but as a general-purpose feature for working with the toolbar.

**Comment by nmielnik** [comment]
Have you tried the [`checkSelection()`](https://github.com/yabwe/medium-editor/blob/master/API.md#checkselection) method on the editor?

**Comment by csarven** [comment]
As I understand `checkSelection()` it appears to be rather primitive to what I'm thinking since it only deals with the state of the button. However, I can see that it would be a good reason to override that method.

An example: Given `<h2>foo</h2>` where the user selects the text 'foo', the toolbar shouldn't pop-up with a `b`/`strong` buttons since adding them inside h2 would be meaningless -  this is meanwhile they would be available in other cases e.g., inside `<p>`.

Perhaps I've misunderstood `checkSelection()` so please let me know if whether something like above is already possible.

Related: see also the context example here http://olivier-m.github.io/minislate/

**Comment by nmielnik** [comment]
Ah, I think something like what @phiggins42 suggested in #668 is what you're looking for.  Right now, there isn't any support for adding/remove buttons from the toolbar based on what type of element is currently selected.  This could be implemented as custom extension similar to the code he shared though.

**Comment by davideanderson** [comment]
I would like this enhancement as well.  In particular, I am working on an extension and need a toolbar for modifying particular element types.  However, I would prefer to be able to add/remove my extension buttons to the main editor toolbar (and also hide built-in buttons that are not appropriate for the selection), rather than having to manage my own toolbar which would be very similar to the existing toolbar with regards to style, placement, etc.

For now, I will go through and manually hide/show the buttons, similar to #668, but having a cleaner way of activating/disabling/showing/hiding toolbar buttons after the editor is already initialized would be nice.

**Comment by nmielnik** [comment]
@davideanderson @phiggins42 @csarven I've created a gitter channel if we want to brainstorm about this: https://gitter.im/nmielnik/797ContextAwareToolbar

**Comment by nmielnik** [comment]
@davideanderson has started a repo for an extension that would allow for this kind of behavior (dynamic buttons based on what type of element is currently being edited).

Repo: https://github.com/davideanderson/medium-editor-toolbar-states
Demo: http://davideanderson.github.io/medium-editor-toolbar-states/

There are some potential issues outlined in the [gitter channel](https://gitter.im/nmielnik/797ContextAwareToolbar), but if anyone wanted to continue development on the extension, or build out their own for others to use, please update this issue!
