### ISSUE TITLE
Anchor preview only working when editor is not focused

### ISSUE THREAD

**Issue by gerherz** [yabwe/medium-editor#825]
I'm having a problem with the anchor preview extension. By using the inspector, I can tell it only works when the editor is not focused. I'm using the 5.8.2 version with this config:

```javascript
{
	elementsContainer: document.getElementById('cont'+this.props.name),
	buttonLabels: 'fontawesome',
	spellcheck: false,
	imageDragging: false,
	anchor: {
		placeholderText: "http://",
		targetCheckbox: true,
		targetCheckboxText: "Abrir en una nueva ventana"
	},
	toolbar: {
		buttons: ['bold', 'italic', 'underline', 'strikethrough', 'subscript', 	'superscript', 'anchor', 'table', 'h2', 'orderedlist', 'unorderedlist', 'justifyLeft', 'justifyCenter', 'justifyRight', 'justifyFull', 'fontcolor', 'embed', 'imagen', 'removeFormat'],
		static: true,
		updateOnEmptySelection: true
	},
	extensions: {
		table: new MediumEditorTables(),
		fontcolor: new MediumEditorForeColor(),
		embed: new MediumEditorEmbed(),
		imagen: new MediumEditorInsertImage()
	},
	autoLink: true,
	paste: {
		cleanPastedHTML: true,
		cleanAttrs: ['class'],
		forcePlainText: false
	}
}
```

**Comment by j0k3r** [comment]
Could you provide a jsfiddle to reproduce the bug ?

**Comment by gerherz** [comment]
Sure: http://jsfiddle.net/ujfev0aj/
It's happening both on Firefox and Chromium.

**Comment by DylanPiercey** [comment]
+1 to this issue.

**Comment by nmielnik** [comment]
So as far as I remember, there was intent around not having the anchor-preview show up when the toolbar is visible. You can see the code that does this [here](https://github.com/yabwe/medium-editor/blob/master/src/js/extensions/anchor-preview.js#L168-L172) within the anchor-preview extension.

The goal of this code was to prevent both the toolbar and the anchor-preview from showing up at the same time, which could be pretty messy in the UI.  Normally, if you focus into the editor but don't select any text, the toolbar will not show up, thus you can hover over an anchor and see the anchor preview.

In this case, you're using both the `toolbar.static: true` and `toolbar.updateOnEmptySelection: true` options.  Because of that, the toolbar will actually be displayed whenever any focus is inside the editor, and since the toolbar is visible, this code prevents the anchor-preview from displaying.

It seems like we'd want to experiment with allowing the anchor-preview to be displayed at any point when the static toolbar is being used, but again I'm not sure what things will look like if the anchor-preview and the toolbar overlap, which could definitely happen if we change this code...

**Comment by DylanPiercey** [comment]
At our company we have completely reskinned the editor and it makes sense in our designs to always have the anchor preview available even when the text area is not in focus.

Ideally this would at least be a configurable option for the anchor preview displaying on hover or on focus and hover.

**Comment by nmielnik** [comment]
Yeah, this could definitely make sense as an additional configuration option.  Something like:

```js
var editor = new MediumEditor('.editor', {
  // ...
  anchorPreview: {
    showWhenToolbarIsVisible: true
  }
});
```

**Comment by gerherz** [comment]
Same thing here. We also have reskinned the editor and have the toolbar as static.
@nmielnik That seems to be a good solution. Is it difficult to implement? Can I help in any way?

**Comment by nmielnik** [comment]
This shouldn't be difficult to implement, please feel free to open a PR!

The changes would mostly be in `anchor-preview.js`, you can see the `if` condition that would need to be changed [here](https://github.com/yabwe/medium-editor/blob/master/src/js/extensions/anchor-preview.js#L168-L172)

You can look at `hideDelay` and `previewValueSelector` as existing anchor-preview options, their default values are defined directly on the prototype at the top of the file (we'd want to default this option to `false` so it doesn't affect existing users).

Thanks, and let us know if you have any other questions.

**Comment by nmielnik** [comment]
There is now a `showWhenToolbarIsVisible` option for the anchor-preview, it was introduced by #839 a while back.
