### ISSUE TITLE
ME's blur event shouldn't fire when users interact with custom extension's toolbar

### ISSUE THREAD

**Issue by litera** [yabwe/medium-editor#830]
I'm writing an ME extension that displays a custom toolbar when caret is on specific elements within *contenteditable* element. I would like to make this extension's toolbar to be part of ME so that interacting with my custom toolbar (clicking) doesn't fire ME's custom *blur* event.

Why do I want that? Similar to ME's own toolbar when you interact outside of the editor, toolbars should hide. That's why I'm also subscribing to ME's *blur* event to hide my custom toolbar.

**But the problem is** that when my toolbar shows up and I click on it, ME regards this as interactivity outside of the editor and fires *blur* event which consequently hides my toolbar that I just clicked on...

It would be best if ME had the ability during extension init phase to also register custom DOM sub-tree that extensions may be using and regard it as ME's DOM. Similar to how it does with anchor preview, and toolbar to determine external event. This is very much baked in to provided extensions, but custom extensions are left out in the cold.

**Excerpt from medium-editor.js** that does this checking
```javascript
// Check if the target is external (not part of the editor, toolbar, or anchorpreview)
var externalEvent = !MediumEditor.util.isDescendant(hadFocus, target, true) &&
					!MediumEditor.util.isDescendant(toolbarEl, target, true) &&
					!MediumEditor.util.isDescendant(previewEl, target, true);
```
This code should be checking custom extensions' registered DOM elements as well... This would be an **ideal solution**.

**But how do I solve this using current ME's behaviour?** I should basically intercept *blur* event somehow and cancel its triggering when I detect that interaction is with my custom toolbar. Or at least that's how I see it.

**Comment by nmielnik** [comment]
@litera would it be possible for your toolbar to be a child of the editor toolbar itself?  This is one way to accomplish what you're talking about.

The `MediumEditor.extensions.form` extension exists to help provide a contract for any extension that wishes to display some UX within the toolbar.

The anchor extension (for example) displays a textbox and some checkboxes whenever the the link button is clicked in the toolbar. It accomplishes by 'extending' the `MediumEditor.extensions.form` object, which gives hooks for hiding/showing the buttons within the toolbar, and display other UX there instead.  It also accomplishes what you're trying to achieve since the custom UX is a child of the toolbar element, thus it won't cause a blur when the user interacts with it.

**Comment by litera** [comment]
That might probably be solved that way, but that's not a viable long term solution. Otherwise not only link form would do it but link preview as well. Why was it decided that link preview doesn't add markup to the same toolbar container? Its behaviour? Well my extension's toolbar is in a way just as different and be hackish to put it on the toolbar as it is a bit more complex. It ads its own toolbar that can be extended on user click and clicking on the extended button it then also shows additional forms etc. I don't think I would like to make it part of existing toolbar complicating things to extreme.

Why is this even a problem? Because when editor looses focus and my toolbar was maybe displayed it has to hide itself. So whenever user starts interacting with anything else than the editor, everything about it should subside.

Actually I would be able to pull it off by preventing event propagation on mousedown on my toolbar if only Medium Editor didn't add an event handler on body element that doesn't bubble (uses event capturing). If that could be changed I could make it without refocusing the editor.

I suspect that the only reason that body uses event capturing is to prevent listeners from cancelling the event so editor wouldn't fire its own custom *blur* event.

**Comment by litera** [comment]
The best thing would be for `MediumEditor.Extension.prototype` to have a function `.registerExtensionToolbar`. This one would internally keep an array of these elements in `MediumEditor.Events.prototype.toolbars` and then simply change `.updateFocus` function to call `isDescendant`on each of these where now there are only three checks. This would be a permanent solution. Of course existing extensions linkPreview and toolbar should be ammended to register their own toolbars.

**Comment by nmielnik** [comment]
So we listen for `mousedown` along with `click` and `focus` on the body using a capture event so that we can accurately detect when anything outside of the editor has happened.  The combination of these series of events makes this possible, as there are a bunch of nasty edge cases about detecting when this should happen.

I definitely agree that this could be a useful feature, I just think we need to be thoughtful about how the functionality is exposed.  I could see how your example of having the extension register with the toolbar could work, but I could also see having the extension expose a method like `getInteractionElements()` which can return the elements that medium-editor should check for interaction with when detecting `blur`.

I think even if you had the extensions register with medium-editor via something like `registerExtensionWithElements()`, the internal code would still need to call into the extension to get the elements to check against each time, so I'm wonder if skipping a register method would make this simpler?

**Comment by litera** [comment]
@nmielnik: My suggestion `registerExtensionToolbar` (or Elements) is somewhat a very similar suggestion to your `getInteractionElements`. They both serve the same purpose. The only difference being that my suggestion relies on extension to do it itself, while your suggestion relies on MediumEditor to ask each extension when adding them. Based on the way how extension work at the moment, your suggestion seems a more consistent way. Internally they'd both work in the same way. They'd save these *interaction elements* in an internal variable (likely an array) and then do the checks against it in `updateFocus` function. This would solve the problem.

For now I monkey patched `MediumEditor.Events.prototype.updateFocus` before making a MediumEditor instance so that I also added my toolbar check and it works as it should. Perfect. But this monkey patching should be checked/changed with each new ME version. That's why a solution using `getInteractionElements` is a much better one. Even *anchor* extension could easily be changed to extract its URL form and make it independent of the toolbar (but this is optional)

**Comment by litera** [comment]
@nmielnik Is there anything else you need from me (as this issue has *awaiting response* label to it)?

**Comment by nmielnik** [comment]
The awaiting response label was removed, I don't think there's anything else you need to update until this enhancement gets added.

**Comment by davideanderson** [comment]
I have also experienced this exact issue and would appreciate this enhancement as well.

**Comment by nmielnik** [comment]
@litera did you ever look into implementing this in a way that we could incorporate into the core code?

**Comment by davideanderson** [comment]
@nmielnik Personally, I think there should be an optional method that extensions can implement, such as your suggested `getInteractionElements()`, which returns null, or an element, or an array of elements.  Then, the `updateFocus()` method in events.js would query all registered extensions, build up an array of interaction elements, and then check to see if event occured in a descendant of any of the interaction elements, just like it currently checks the toolbar element and the anchor preview element.  It seems like a relatively straight forward solution, though I have just started digging into the medium-editor code this week, so I am not quite at the point that I would be comfortable submitting a pull request as I don't know the potential scope of any side-effects/consequences of such a change.

**Comment by nmielnik** [comment]
@davideanderson if you're adding code that looks for a new method on extensions, the chances of it causing problems are pretty low.  Only in cases where existing extensions created a method named 'getInteractionElements()` would there be a problem, so I wouldn't worry much about it.

As described, I think just adding code that calls `getInteractionElements()` on each extension (if the method exists) and then using the result of those calls when checking if the event occurred on any descendants is all we would need.  The only other thing that would need to happen would be updating the documentation ([`src/js/extensions/README.md`](https://github.com/yabwe/medium-editor/blob/master/src/js/extensions/README.md))

**Comment by litera** [comment]
@nmielnik Of course not. I haven't done anything as I explicitly asked you if you need me to do anything and you declined. You should ask me to create a pull request for this... :) Maybe it was a misunderstanding.

**Comment by nmielnik** [comment]
Ah, @litera definitely a misunderstanding!  I was commenting that I removed the 'awaiting response' label from the issue because I didn't think there was anything else you needed to clarify in this github issue (the requirements are super clear thanks you!)

I apologize, the last thing in the world I want is for anyone to not submit a PR because of me!

It seems like @davideanderson voted for the idea of doing `getInteractionElements()`, so if we were still debating between the 2 it'd have my vote, but I would certainly accept a PR for either implementation!

**Comment by litera** [comment]
@nmielnik Let that be it. I'll create a PR as soon as possible. Just as I *climb out of my hole* of stuff to complete.

**Comment by nmielnik** [comment]
@litera and @davideanderson, the code for this is ready t be merged in (pending code review).  Let me know what you fellas think: #1108
