### ISSUE TITLE
Last newline is temporarily not shown when medium editor is attached to a PRE

### ISSUE THREAD

**Issue by dcsaszar** [yabwe/medium-editor#833]
Fiddle: http://jsfiddle.net/yjpbn37s/10/

When entering a trailing newline into a `PRE` with medium-editor, the newline is temporarily not visible.
It becomes visible for a short moment, then is hidden until the user enters further text.

Disclaimer: I don't know if attaching medium-editor to a `PRE` is a valid use-case at all.

**Comment by nmielnik** [comment]
@dcsaszar generally the editor initialized using a `<div>` as the editor target element.  You could always do something like:

```html
<div class="editor">
    <pre>Initial Content</pre>
</div>
```

and passing the `.editor` div as the editor element into MediumEditor.  Would that satisfy your use case?

**Comment by dcsaszar** [comment]
I'm trying to let a user edit the content of a `PRE` (with a reasonable subset of medium editor functionality)

I see two ways we could go:

1. The suggested workaround has the drawback that, it allows the user to convert the `PRE` into non-`PRE` HTML.
I need to add some pre- and post-processing, including forcing `PRE`-like styling to the outer `DIV`.
Not the most elegant solution, but doable. Maybe we should add a note to the `README`.

2. Since the `README` doesn't currently indicate that `.editable` needs to be a `div`. And given the fact that it mostly works (see fiddle, using `shift`-Enter for newlines), maybe the issue can be fixed. Medium editor could detect the tag it's on. If it's a `PRE` the editor would force the `shift`ed behavior for newlines.

**Comment by nmielnik** [comment]
1) You should be able to hide the buttons in the toolbar that would convert your `<pre>` into another tag.  If you remove the `h1`, `h2`, `pre`, `blockquote`, etc buttons, then the user shouldn't be able to change them, would this be acceptable in this case?

2) As far as I know we haven't called out that you should use a `<div>` because we weren't aware of issues with other element types, and haven't tried any ourselves (until you've brought up this issue)!  Regarding what you said about handling <kbd>ENTER</kbd> and <kbd>SHIFT</kbd> + <kbd>ENTER</kbd>, there have been a bunch of discussions around this in #70, #34, and #251, so any solution for handling this would definitely be useful, even beyond this specific use case.

**Comment by dcsaszar** [comment]
re 1) Added the workaround to the fiddle, and it seems feasible (http://jsfiddle.net/yjpbn37s/11/). With this solution we must post-process the edited text on our side anyway (i. e. convert the editor content back into a single `PRE`). So, a user deleting the `PRE` doesn't make a difference.
