### ISSUE TITLE
Button Demo without Rangy?

### ISSUE THREAD

**Issue by DaveRevay2** [yabwe/medium-editor#880]
The button demo (https://github.com/yabwe/medium-editor/blob/master/src/js/extensions/WALKTHROUGH-BUTTON.md) uses rangy. This is not a dependency for the rest of the editor so it seems strange that is is needed here when many other built in buttons have similar functionality.

Is there some way to accomplish the same thing without needing the Rangy library?

``` 
    this.classApplier = rangy.createCssClassApplier('highlight', {
        elementTagName: 'mark',
        normalize: true
    });
```

**Comment by nmielnik** [comment]
So, there may be a simple way to accomplish this, but I can't think of it off the top of my head, thus why it was quick and easy to just use rangy for the demo (the demo is more of a guide to how buttons work, not a guide on how to manipulate the contents of the editor).

So, I would say this issue would suggest 2 things:
1. Create some utility method that allows for wrapping/unwrapping a selection with a tag name
2. Update the demo to use this functionality instead of using rangy.

**Comment by anilmaurya** [comment]
@nmielnik Does `medium-editor` really needs wrapping/unwrapping utility ?

Highlight button can be implemented using execCommand `HiliteColor` and `BackColor` api. 

Demo: http://jsfiddle.net/timdown/Bvd9d/

**Comment by nmielnik** [comment]
So there are definitely other ways to introduce 'highlighting' outside of the `<mark>` tag and using the class applier.  

The fiddle you provided works in that in Firefox & Chrome you get a `<span style="backgroundcolor: <hexcolor>">` that wraps the selection.  In IE, the result is `<font style="backgroundcolor: <hexcolor>">`.

These can definitely work, and I'm assuming there's better undo/redo support for this.  However, in the interest of a demo, using the class applier to wrap a tag makes the demo easier to follow, since it minimizes the code to actually accomplish the highlighting, and allows the demo to focus on the API that buttons have. 

What makes the proposed approach even more complicated is for handling the case where the button in the toolbar should be 'active' whenever the selection contains highlighted text.  Since the browsers use style attributes and either `<span>` or `<font>` elements, the code would have to climb the tree, and when it hits a `<span>` or `<font>` inspect the computed styles to see if the color has been set, and if it's set to the expected value.

Again, this could definitely all work, but I don't think it's simple enough for a demo of how buttons work in medium-editor. That's my $0.02 anyway.

**Comment by anilmaurya** [comment]
Agreed, it makes sense to keep demo as simple as possible.

But adding utility to remove a dependency from a demo does not make sense to me.

And to answer @DaveRevay2 question:

`Is there some way to accomplish the same thing without needing the Rangy library?`

Yes, there are plenty of others way to accomplish same thing without Rangy but with Rangy its much simple and clean.

**Comment by nmielnik** [comment]
So I agree that adding a utility to remove a dependency from a demo doesn't make sense.

However, a utility that allows us to wrap a selection with an element, or an element with a class name, would be extremely useful in other parts of our code.  It would also allow us to do things like changing font name, font size, background color, etc. in a much simpler way.

In short, adding a utility method to wrap selection in an element and/or class is one of the top 2 or 3 things I think would help our code base, and that's without even thinking about the demo.  That's primarily why I would like this class applier functionality.

**Comment by anilmaurya** [comment]
Ok, this answer my question `Does medium-editor really needs wrapping/unwrapping utility ?` which was missing in earlier response.

I will try to work on this in coming weekend.

**Comment by nmielnik** [comment]
@anilmaurya I'm closing this issue and opening a new enhancement request (#910) to make it easier to track progress and get some suggestions and/or help
