### ISSUE TITLE
Bold button apparently not working properly if <b> has different font-weight, even when configuration is overriden.

### ISSUE THREAD

**Issue by 2mittens** [yabwe/medium-editor#908]
Hello all!

I'm using 400 as font-weight for the `<b>` as I'm also using 300 for normal text.
This, of course, is breaking the queryCommandState and the B button, so I tried this configuration to fix things:
```js
var editor = new MediumEditor('.editable', {
	toolbar: {
		buttons: [
			'h2', 'h3', {
				name: 'bold',
				action: 'bold',
				aria: 'bold',
				tagNames: ['b', 'strong'],
				useQueryState: false,
				contentDefault: '<b>B</b>',
				contentFA: '<i class="fa fa-bold"></i>'
			}, 'italic', 'underline', 'quote'
		]
	},
	autoLink: true,
	placeholder: {
		text: 'Start writing...'
	}
});
```
Unluckily it's not working.

The `<b>` is added, and the button on the toolbar keeps the active state, but once is active, you can't disable/remove the state.
Instead it keeps adding new `<b>` or replacing the current one.

Tried also to specify styles on the button configuration like this
```js
style: {
    prop: 'font-weight',
    value: '400'
}
```
without success either.

**Comment by nmielnik** [comment]
So @2mittens this is an especially problematic problem you're trying to solve.  In my org, we've battled this problem and have chosen to just avoid doing anything with font-weight.  Thus, standard text is '400' and bold is '700'.

If you want to attempt to alter the font-weight for bolding, I would start with css:

```css
.editable {
    font-weight: 300;
}
.editable b,
.editable strong {
    font-weight: 400;
}
```

This let's you set the default font-weight to 300, and controls what font-weight `<b>` and `<strong>` tags will have.

If you do this, I think you can get medium-editor to behave the way you want it to for the bold button as long as you use this as the configuration (which is the same configuration you listed above):

```js
{
    name: 'bold',
    action: 'bold',
    aria: 'bold',
    tagNames: ['b', 'strong'],
    useQueryState: false,
    contentDefault: '<b>B</b>',
    contentFA: '<i class="fa fa-bold"></i>'
}
```

Give that a try and see what you find.

(More context if you're interested)
The reason to set `useQueryState` to false is that if you mess with font-weight, you can no longer depend on the browser to help determine whether text is bold or not. The problem stems from the fact that we're depending on the browser to bold things.  The browsers will attempt to bold text by wrapping the text in a `<b>` or `<strong>` tag.  However, if you ask the browser if the current text is bold (via `document.queryCommandState()`), it won't look at tags but instead will look at the computed style for the text.  From there, the browser is likely looking to see is the font weight 700 or 400 to determine if it's bold or not bold.

**Comment by 2mittens** [comment]
Thanks for the reply @nmielnik!

I forgot to add the css I'm using, but is exactly the same as yours (I changed from 400 to 300 and 700 to 400 for design reasons).

I already knew the behavior of `document.queryCommandState()` (but thanks for the explanation anyway, I really appreciated!) and for that reason my first thought was to disable it.

Unluckily this isn't working. Just checked also with your configuration to be 100% sure.

Here a http://codepen.io/2mittens/pen/YwwQPP if it helps!

**Comment by nmielnik** [comment]
So yeah, looking at your fiddle it seems like the browser just can't handle this case. When you click the bold button, ultimately `document.execCommand('bold', null, false)` will be executed, normally, the browser figures out if it needs to bold or unbold on its own.  My suspicion is that for similar reasons as to why `queryCommandState()` would return an incorrect value, when the browser is trying to determine how to bold and unbold it looks at the computed style.

So when `execCommand()` gets called, it sees the font-weight is 300, and inserts the `<b>` tag.  But then, when you call `execCommand()` again, it sees a font-weight of 400, and thus thinks the text is not bold, and tries to add another `<b>` tag (which I'm guessing it ends up not doing since there's an existing `<b>` tag there already??)

This is all just a guess, but this does seem consistent with some issues I've run into when using this at my org.  I think you're going to run into trouble in general when modifying default text font-weight to be anything other than 400...

**Comment by 2mittens** [comment]
Well, I guess I'm going to leave 700 as font-weight for `<b>` and 300 for everything else, no big deal.

Thank you anyway!
