### ISSUE TITLE
editor is not defined in Meteor.

### ISSUE THREAD

**Issue by abhisheksoni27** [yabwe/medium-editor#921]
The editro works perfectly, but when I try to use `editor.serialize()` in `Template.nameofthetemplate.events({})` block, it says editor is not defined. When I actually add the `var editor = new MediumEditor(".editable");`, 
then, `console.log(content['element-0'].value);`

 returns `null`.

**Comment by nmielnik** [comment]
I'm not familiar with meteor but this kind of sounds like you're losing a reference to the `editor` variable? If so, I'm not sure if this is a medium-editor issue or not.

One thing you can check, is see what's in the `window._mediumEditors` array.  Each instance of medium-editor that is created ends up in there.  So, if at the point in your code where 'editor' is not defined, if you see the instance still in the `window._mediumEditors` array, then your issue is not a medium-editor problem, but something with how meteor or your project is keeping a reference to it.

**Comment by patrickml** [comment]
@abhisheksoni27 what you need to do is add the editor to a rendered function like so

```js
Template.name.onRendered(function () {
   this.editor = new MediumEditor(".editable");
});
```

Then on the events you should be able to reference it like so
```js
Template.name.events({
'click .someSelector' : function (event, template) {
  template.editor.serialize();
}
});
```
