### ISSUE TITLE
Event `editableInput` doesn't fire on autoLink

### ISSUE THREAD

**Issue by goldensunliu** [yabwe/medium-editor#959]
when `autoLink` is true, on auto linking Event `editableInput` is never fired, are we expecting some other event to be fired?

**Comment by nmielnik** [comment]
I wasn't able to reproduce this locally, could you mention what browser and version of medium-editor you're using?

Also, if you can get this to reproduce in a codepen / jsfiddle / jsbin, that'd be awesome, thanks!

**Comment by goldensunliu** [comment]
here is a code pen using the latest packages:
http://codepen.io/poda/pen/wMQbZw

type any any link for the editor to pick it up, e.g www.google.com.

the code will output the content's html on each `editableInput` event, you will noticed it doesn't fire on autolink when the element loses focus and the link is transformed.

**Comment by nmielnik** [comment]
Ahhh ok, now I understand what you're seeing...this is definitely a bug, thanks for pointing it out!

The issue is that the auto-link extension doesn't call the core `createLink()` method within `core.js`.  That method handles manually triggering `editableInput` correctly.  

The auto-link extension calls `MediumEditor.util.createLink()` to build an anchor and move all of the text-nodes into that anchor.  It then takes the resulting anchor element and inserts it into the editor, but doesn't manually trigger `editableInput`.

The reason why we hadn't noticed this was because the cases we've tried always involved typing space or return, which results in `editableInput` being triggered because we've added a space or a newline and not because auto-link happened...that masked the bug.

Two potential fixes:
1. Instead of inserting the anchor into the html manually, the code could build the anchor and then use `document.execCommand('insertHTML')` to insert it.  This would cause `editableInput` to be triggered.
2.The `createAutoLink` method in the auto-link extension could manually trigger `editableInput` once it has inserted the link into the editor.

Nice catch and thanks again for opening an issue!
