### ISSUE TITLE
Display placeholder when text removed

### ISSUE THREAD

**Issue by JasonTheAdams** [yabwe/medium-editor#970]
Since the placeholder is attempting to mimic a standard input, it would make sense and be useful for the placeholder to display again if the user removes all the text within the editor.

**Comment by j0k3r** [comment]
It should work like that.
Do you have such a behavior using [our demo](https://yabwe.github.io/medium-editor/demo.html)? If yes, could you told us at least your browser and steps to reproduce.

**Comment by JasonTheAdams** [comment]
Hmm.. nope, not working on the demo either.

System: OS X 10.11.3
Browser: Chrome 48.0.2564.97 (64-bit)

Steps:
- Load editor with existing text
- Select all text and delete

If you continue to push backspace it "twitches". It ends up with a paragraph that contains a `<br>` tag.

**Comment by 1u** [comment]
Same problem here. The Placeholder appears only after the field loses focus. 

We expect placeholder to disappear only after starting to type (not already when field gets focus), 
and to appear as soon as field is empty (not only if field loses focus).

@JasonTheAdams: this is the same thing you address, right?

**Comment by 1u** [comment]
We found a hidden config option here: #534

**Comment by nmielnik** [comment]
Oops, guess that feature got added and we forgot to update the documentation!

@1u since you found this, would you be interested in opening a PR to add it to [`OPTIONS.md`](https://github.com/yabwe/medium-editor/blob/master/OPTIONS.md#placeholder-options) and [`README.md`](https://github.com/yabwe/medium-editor/blob/master/README.md#placeholder-options)?

@JasonTheAdams will this option (added in #534) work for you?

**Comment by 1u** [comment]
Yup, I'll do that.

**Comment by JasonTheAdams** [comment]
@1u Thanks for finding that! I have to use the inspector to make sure it works as the default placeholder text is white, but that did the trick. @nmielnik Wouldn't it make more sense to have the default as a gray?

Anyway, working now so I'll close the ticket. :)
